use std::fmt::Write;
use std::path::Path;

use crate::IndexError;

/// Tables in the `dbt` schema (snapshot semantics).
pub const DBT_TABLES: &[&str] = &[
    "generation",
    "project",
    "packages",
    "project_vars",
    "project_env_vars",
    "nodes",
    "node_columns",
    "edges",
    "column_lineage",
    "node_input_files",
    "test_metadata",
    "exposures",
    "metrics",
    "groups",
    "macros",
    "semantic_models",
    "semantic_entities",
    "semantic_measures",
    "semantic_dimensions",
    "time_spines",
    "semantic_relationships",
    "saved_queries",
    "unit_tests",
    "docs",
    "catalog_tables",
    "catalog_stats",
    "column_stats",
    "sample_data",
    "source_freshness",
    "context",
    "context_terms",
    "context_links",
];

/// Tables in the `dbt_rt` schema (snapshot — overwritten each invocation).
pub const DBT_RT_TABLES: &[&str] = &[
    "invocations",
    "invocation_nodes",
    "run_results",
    "diagnostics",
    "adapter_queries",
    "test_failures",
];

/// Generate a static `views.sql` covering the full schema.
///
/// Every table always has a parquet file, so no conditional logic is needed —
/// the file is the same regardless of what data was ingested.
pub fn write_views_sql(dir: &Path) -> Result<(), IndexError> {
    let mut sql = String::from(
        "-- Auto-generated by dbt-index. Query with:\n\
         --   duckdb -cmd \".read views.sql\"\n\n\
         CREATE SCHEMA IF NOT EXISTS dbt;\n\
         CREATE SCHEMA IF NOT EXISTS dbt_rt;\n\n",
    );

    // dbt.* — single-file views
    for table in DBT_TABLES {
        writeln!(
            sql,
            "CREATE OR REPLACE VIEW dbt.{table} AS \
             SELECT * FROM read_parquet('dbt.{table}.parquet');",
        )
        .unwrap();
    }
    writeln!(sql).unwrap();

    // dbt_rt.* — single-file views (same as dbt.*)
    for table in DBT_RT_TABLES {
        writeln!(
            sql,
            "CREATE OR REPLACE VIEW dbt_rt.{table} AS \
             SELECT * FROM read_parquet('dbt_rt.{table}.parquet');",
        )
        .unwrap();
    }

    // Analytical views
    sql.push_str(ANALYTICAL_VIEWS);

    std::fs::write(dir.join("views.sql"), sql)?;
    Ok(())
}

/// Analytical views — always emitted since all base tables always exist.
const ANALYTICAL_VIEWS: &str = "
CREATE OR REPLACE VIEW dbt_rt.run_results_latest AS
SELECT * FROM dbt_rt.run_results
WHERE NOT (status = 'error' AND execution_time = 0)
QUALIFY ROW_NUMBER() OVER (PARTITION BY unique_id ORDER BY created_at DESC) = 1;

CREATE OR REPLACE VIEW dbt_rt.dag_validity AS
WITH latest AS (
    SELECT r.unique_id, r.status, r.invocation_id, i.generated_at
    FROM dbt_rt.run_results r
    JOIN dbt_rt.invocations i ON r.invocation_id = i.invocation_id
    QUALIFY ROW_NUMBER() OVER (PARTITION BY r.unique_id ORDER BY r.created_at DESC) = 1
)
SELECT
    child.unique_id, child.status,
    child.generated_at AS child_built_at,
    parent.unique_id AS parent_unique_id,
    parent.generated_at AS parent_built_at,
    child.generated_at >= parent.generated_at AS parent_is_fresh
FROM latest child
LEFT JOIN dbt.edges e ON e.child_unique_id = child.unique_id
LEFT JOIN latest parent ON e.parent_unique_id = parent.unique_id;

CREATE OR REPLACE VIEW dbt_rt.node_status AS
SELECT
    n.unique_id, n.name, n.resource_type,
    n.ingested_at AS parsed_at, n.compiled_at,
    r.created_at AS run_at, r.invocation_id AS run_invocation_id,
    r.status AS run_status, r.execution_time AS run_execution_time, r.message AS run_message,
    CASE
        WHEN r.created_at IS NOT NULL AND n.compiled_at IS NOT NULL AND r.created_at >= n.compiled_at THEN 'run'
        WHEN n.compiled_at IS NOT NULL THEN 'compiled'
        ELSE 'parsed'
    END AS effective_phase,
    CASE
        WHEN n.compiled_at IS NOT NULL AND n.ingested_at > n.compiled_at THEN true
        WHEN r.created_at IS NOT NULL AND n.compiled_at IS NOT NULL AND n.compiled_at > r.created_at THEN true
        ELSE false
    END AS is_stale
FROM dbt.nodes n
LEFT JOIN dbt_rt.run_results_latest r ON n.unique_id = r.unique_id;

CREATE OR REPLACE VIEW dbt.nodes_enriched AS
SELECT
    n.*, r.status AS last_run_status, r.execution_time AS last_execution_time,
    r.invocation_id AS last_invocation_id,
    ct.table_type AS catalog_table_type, ct.table_owner AS catalog_owner
FROM dbt.nodes n
LEFT JOIN dbt_rt.run_results_latest r ON n.unique_id = r.unique_id
LEFT JOIN dbt.catalog_tables ct ON n.unique_id = ct.unique_id;

CREATE OR REPLACE VIEW dbt.tests_enriched AS
SELECT
    n.unique_id, n.name AS test_name,
    tm.test_name AS test_type, tm.test_namespace, tm.column_name,
    tm.attached_node, tm.severity, tm.kwargs,
    target.name AS target_node_name, target.resource_type AS target_resource_type,
    r.status AS last_run_status, r.message AS last_run_message, r.failures AS last_run_failures,
    tf.failure_rows
FROM dbt.nodes n
JOIN dbt.test_metadata tm ON n.unique_id = tm.unique_id
LEFT JOIN dbt.nodes target ON tm.attached_node = target.unique_id
LEFT JOIN dbt_rt.run_results_latest r ON n.unique_id = r.unique_id
LEFT JOIN dbt_rt.test_failures tf ON n.unique_id = tf.unique_id AND r.invocation_id = tf.invocation_id
WHERE n.resource_type IN ('test');
";
