/*
 * dbt Cloud API v3
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: support@getdbt.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectEnveloped {
    #[serde(rename = "data")]
    pub data: Box<models::ProjectResponse>,
    #[serde(rename = "status")]
    pub status: Box<models::ResponseStatus>,
}

impl ProjectEnveloped {
    pub fn new(data: models::ProjectResponse, status: models::ResponseStatus) -> ProjectEnveloped {
        ProjectEnveloped {
            data: Box::new(data),
            status: Box::new(status),
        }
    }
}
