/*
 * dbt Cloud API v3
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: support@getdbt.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectResponse {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    /// The name of the project
    #[serde(rename = "name")]
    pub name: String,
    /// The account the project is associated with
    #[serde(rename = "account_id")]
    pub account_id: i64,
    /// The description of the project
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The active connection
    #[serde(rename = "connection_id", skip_serializing_if = "Option::is_none")]
    pub connection_id: Option<i64>,
    /// The active repository
    #[serde(rename = "repository_id", skip_serializing_if = "Option::is_none")]
    pub repository_id: Option<i64>,
    /// The active semantic layer configuration
    #[serde(
        rename = "semantic_layer_config_id",
        skip_serializing_if = "Option::is_none"
    )]
    pub semantic_layer_config_id: Option<i64>,
    /// A value of 1 means this entity is active and a value of 2 means this entity is deleted
    #[serde(rename = "state", skip_serializing_if = "Option::is_none")]
    pub state: Option<i32>,
    /// The path in the associated repository where a dbt project can be found
    #[serde(
        rename = "dbt_project_subdirectory",
        skip_serializing_if = "Option::is_none"
    )]
    pub dbt_project_subdirectory: Option<String>,
    /// The job used for docs generation
    #[serde(rename = "docs_job_id", skip_serializing_if = "Option::is_none")]
    pub docs_job_id: Option<i64>,
    /// The job used for source freshness generation
    #[serde(rename = "freshness_job_id", skip_serializing_if = "Option::is_none")]
    pub freshness_job_id: Option<i64>,
    /// The type of the project  * `0` - DEFAULT * `1` - HYBRID
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<models::Type24eEnum>,
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
    // Heavy nested resources (connection, environments, repository,
    // group_permissions) are kept untyped until a caller needs them, matching
    // this crate's curated-subset approach.
    #[serde(rename = "connection", skip_serializing_if = "Option::is_none")]
    pub connection: Option<serde_json::Value>,
    #[serde(rename = "environments", skip_serializing_if = "Option::is_none")]
    pub environments: Option<Vec<serde_json::Value>>,
    #[serde(rename = "repository", skip_serializing_if = "Option::is_none")]
    pub repository: Option<serde_json::Value>,
    #[serde(rename = "group_permissions", skip_serializing_if = "Option::is_none")]
    pub group_permissions: Option<Vec<serde_json::Value>>,
}

impl ProjectResponse {
    pub fn new(name: String, account_id: i64) -> ProjectResponse {
        ProjectResponse {
            id: None,
            name,
            account_id,
            description: None,
            connection_id: None,
            repository_id: None,
            semantic_layer_config_id: None,
            state: None,
            dbt_project_subdirectory: None,
            docs_job_id: None,
            freshness_job_id: None,
            r#type: None,
            created_at: None,
            updated_at: None,
            connection: None,
            environments: None,
            repository: None,
            group_permissions: None,
        }
    }
}
