[tool.setuptools]
package-dir = {"" = "core"}
include-package-data = true

[tool.setuptools.packages.find]
where = ["core"]
include = [
    "dbt",
    "dbt.*",
]

[tool.setuptools.dynamic]
version = { attr = "dbt.version.__version__" }
[project]
name = "dbt-core"
dynamic = ["version"]
description = "With dbt, data analysts and engineers can build analytics the way engineers build applications."
readme = "core/README.md"
requires-python = ">=3.10"
license = { file = "License.md" }
keywords = []
authors = [
    { name = "dbt Labs", email = "info@dbtlabs.com" },
]
maintainers = [
    { name = "dbt Labs", email = "info@dbtlabs.com" },
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
    "agate>=1.7.0,<1.10",
    "Jinja2>=3.1.3,<4",
    "mashumaro[msgpack]>=3.9,<3.15",
    "click>=8.0.2,<9.0",
    "jsonschema>=4.19.1,<5.0",
    "networkx>=2.3,<4.0",
    "protobuf>=6.0,<7.0",
    "requests<3.0.0",
    "snowplow-tracker>=1.0.2,<2.0",
    "pathspec>=0.9,<0.13",
    "sqlparse>=0.5.0,<0.6.0",
    "dbt-extractor>=0.5.0,<=0.6",
    "dbt-semantic-interfaces>=0.10.0,<0.11",
    "dbt-common>=1.27.0,<2.0",
    "dbt-adapters>=1.15.5,<2.0",
    "dbt-protos>=1.0.375,<2.0",
    "pydantic<3",
    "packaging>20.9",
    "pytz>=2015.7",
    "pyyaml>=6.0",
    "daff>=1.3.46",
    "typing-extensions>=4.4",
]

[project.urls]
Homepage = "https://github.com/dbt-labs/dbt-core"
Repository = "https://github.com/dbt-labs/dbt-core.git"
Issues = "https://github.com/dbt-labs/dbt-core/issues"
Changelog = "https://github.com/dbt-labs/dbt-core/blob/main/CHANGELOG.md"

[project.scripts]
dbt = "dbt.cli.main:cli"
[build-system]
requires = [
    "setuptools>=61",
    "wheel",
]
build-backend = "setuptools.build_meta"

[tool.mypy]
# TODO: widen range of files as we fix issues
files = 'core/dbt'
mypy_path = "third-party-stubs/"
namespace_packages = true

[tool.black]
line-length = 99
target-version = ['py38']
