# Root-level pyproject.toml for tool configurations
# Packaging configuration is in core/pyproject.toml
# This file exists so tools like mypy and black can find their config when run from root

[tool.mypy]
# TODO: widen range of files as we fix issues
files = 'core/dbt'
mypy_path = "third-party-stubs/"
namespace_packages = true
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = [
    "dbtlabs.*",
    "dbt_semantic_interfaces.*",
    "dbt_common.*",
    "click.parser",
]
ignore_missing_imports = true

[[tool.mypy.overrides]]
# Mirror legacy mypy behaviour by excluding modules previously unchecked in the pre-commit mirror environment.
module = [
    "dbt.events.types",
    "dbt.events.core_types_pb2",
    "dbt.jsonschemas.jsonschemas",
    "dbt.cli.option_types",
    "dbt.cli.options",
    "dbt.cli.flags",
    "dbt.utils.utils",
    "dbt.env_vars",
    "dbt.context.providers",
    "dbt.artifacts.resources.v1.semantic_layer_components",
]
ignore_errors = true

[tool.black]
line-length = 99
target-version = ['py38']
