import decimal
from typing import Any

class SerializableType: ...
class GenericSerializableType: ...

class SerializationStrategy:
    def serialize(self, value) -> Any: ...
    def deserialize(self, value) -> Any: ...

class RoundedDecimal(SerializationStrategy):
    exp: Any
    rounding: Any
    def __init__(self, places: Any | None = ..., rounding: Any | None = ...) -> None: ...
    def serialize(self, value) -> str: ...
    def deserialize(self, value: str) -> decimal.Decimal: ...
