// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file dbtlabs/proto/public/v1/events/fusion/asset/asset.proto (package v1.public.events.fusion.asset, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { ExecutionPhase } from "../phase/phase_pb";
import { file_dbtlabs_proto_public_v1_events_fusion_phase_phase } from "../phase/phase_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file dbtlabs/proto/public/v1/events/fusion/asset/asset.proto.
 */
export const file_dbtlabs_proto_public_v1_events_fusion_asset_asset: GenFile = /*@__PURE__*/
  fileDesc("CjdkYnRsYWJzL3Byb3RvL3B1YmxpYy92MS9ldmVudHMvZnVzaW9uL2Fzc2V0L2Fzc2V0LnByb3RvEh12MS5wdWJsaWMuZXZlbnRzLmZ1c2lvbi5hc3NldCLCAQoLQXNzZXRQYXJzZWQSFAoMcGFja2FnZV9uYW1lGAEgASgJEgwKBG5hbWUYAiABKAkSFQoNcmVsYXRpdmVfcGF0aBgDIAEoCRIUCgxkaXNwbGF5X3BhdGgYBCABKAkSFgoJdW5pcXVlX2lkGAUgASgJSACIAQESPAoFcGhhc2UYBiABKA4yLS52MS5wdWJsaWMuZXZlbnRzLmZ1c2lvbi5waGFzZS5FeGVjdXRpb25QaGFzZUIMCgpfdW5pcXVlX2lkQkBaPmdpdGh1Yi5jb20vZGJ0LWxhYnMvcHJvdG8tZ29sYW5nL3YxL3B1YmxpYy9ldmVudHMvZnVzaW9uL2Fzc2V0YgZwcm90bzM", [file_dbtlabs_proto_public_v1_events_fusion_phase_phase]);

/**
 * Span event tracking parsing of a single asset.
 *
 * @generated from message v1.public.events.fusion.asset.AssetParsed
 */
export type AssetParsed = Message<"v1.public.events.fusion.asset.AssetParsed"> & {
  /**
   * Package name that owns this asset.
   *
   * @generated from field: string package_name = 1;
   */
  packageName: string;

  /**
   * Asset name (typically the file stem).
   *
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * Path to the asset relative to the project root.
   *
   * @generated from field: string relative_path = 3;
   */
  relativePath: string;

  /**
   * Display path used for CLI progress output.
   *
   * @generated from field: string display_path = 4;
   */
  displayPath: string;

  /**
   * Unique identifier for this asset when available.
   *
   * @generated from field: optional string unique_id = 5;
   */
  uniqueId?: string;

  /**
   * Execution phase for this event.
   *
   * @generated from field: v1.public.events.fusion.phase.ExecutionPhase phase = 6;
   */
  phase: ExecutionPhase;
};

/**
 * Describes the message v1.public.events.fusion.asset.AssetParsed.
 * Use `create(AssetParsedSchema)` to create a new message.
 */
export const AssetParsedSchema: GenMessage<AssetParsed> = /*@__PURE__*/
  messageDesc(file_dbtlabs_proto_public_v1_events_fusion_asset_asset, 0);

