// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file dbtlabs/proto/public/v1/common/vortex_telemetry_contexts.proto (package v1.public.common.vortex_telemetry_contexts, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_dbtlabs_proto_public_v1_events_vortex } from "../events/vortex_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file dbtlabs/proto/public/v1/common/vortex_telemetry_contexts.proto.
 */
export const file_dbtlabs_proto_public_v1_common_vortex_telemetry_contexts: GenFile = /*@__PURE__*/
  fileDesc("Cj5kYnRsYWJzL3Byb3RvL3B1YmxpYy92MS9jb21tb24vdm9ydGV4X3RlbGVtZXRyeV9jb250ZXh0cy5wcm90bxIqdjEucHVibGljLmNvbW1vbi52b3J0ZXhfdGVsZW1ldHJ5X2NvbnRleHRzItECCh5Wb3J0ZXhUZWxlbWV0cnlEYnRDbG91ZENvbnRleHQSEAoIZXZlbnRfaWQYASABKAkSDwoHZmVhdHVyZRgCIAEoCRIiChpzbm93cGxvd19kb21haW5fc2Vzc2lvbl9pZBgDIAEoCRIfChdzbm93cGxvd19kb21haW5fdXNlcl9pZBgEIAEoCRISCgpzZXNzaW9uX2lkGAUgASgJEhQKDHJlZmVycmVyX3VybBgGIAEoCRIcChRkYnRfY2xvdWRfYWNjb3VudF9pZBgHIAEoCRIkChxkYnRfY2xvdWRfYWNjb3VudF9pZGVudGlmaWVyGAggASgJEhwKFGRidF9jbG91ZF9wcm9qZWN0X2lkGAkgASgJEiAKGGRidF9jbG91ZF9lbnZpcm9ubWVudF9pZBgKIAEoCRIZChFkYnRfY2xvdWRfdXNlcl9pZBgLIAEoCSJ3ChxWb3J0ZXhUZWxlbWV0cnlDb21tb25Db250ZXh0EhoKEmFjY291bnRfaWRlbnRpZmllchgBIAEoCRISCgpwcm9qZWN0X2lkGAIgASgJEhYKDmVudmlyb25tZW50X2lkGAMgASgJEg8KB3VzZXJfaWQYBCABKAlCTVpLZ2l0aHViLmNvbS9kYnQtbGFicy9wcm90by1nb2xhbmcvdjEvcHVibGljL2NvbW1vbi92b3J0ZXhfdGVsZW1ldHJ5X2NvbnRleHRzYgZwcm90bzM", [file_dbtlabs_proto_public_v1_events_vortex]);

/**
 * @generated from message v1.public.common.vortex_telemetry_contexts.VortexTelemetryDbtCloudContext
 */
export type VortexTelemetryDbtCloudContext = Message<"v1.public.common.vortex_telemetry_contexts.VortexTelemetryDbtCloudContext"> & {
  /**
   * event_id is the unique identifier for this event. It is a generated UUID.
   *
   * @generated from field: string event_id = 1;
   */
  eventId: string;

  /**
   * feature/product name emitting the telemetry event
   *
   * @generated from field: string feature = 2;
   */
  feature: string;

  /**
   * The snowplow domain session ID. This can be used to join these events with snowplow events.
   *
   * @generated from field: string snowplow_domain_session_id = 3;
   */
  snowplowDomainSessionId: string;

  /**
   * The snowplow domain user ID. This can be used to join these events with snowplow events.
   *
   * @generated from field: string snowplow_domain_user_id = 4;
   */
  snowplowDomainUserId: string;

  /**
   * A session ID that can be used to correlate events that were emmitted by the same
   * user during the same session.
   *
   * @generated from field: string session_id = 5;
   */
  sessionId: string;

  /**
   * The URL of the page the user was on when telemetry event was sent
   *
   * @generated from field: string referrer_url = 6;
   */
  referrerUrl: string;

  /**
   * dbt Cloud account ID
   *
   * @generated from field: string dbt_cloud_account_id = 7;
   */
  dbtCloudAccountId: string;

  /**
   * dbt Cloud account identifier
   *
   * @generated from field: string dbt_cloud_account_identifier = 8;
   */
  dbtCloudAccountIdentifier: string;

  /**
   * dbt Cloud project ID
   *
   * @generated from field: string dbt_cloud_project_id = 9;
   */
  dbtCloudProjectId: string;

  /**
   * dbt Cloud environment ID
   *
   * @generated from field: string dbt_cloud_environment_id = 10;
   */
  dbtCloudEnvironmentId: string;

  /**
   * dbt Cloud user ID
   *
   * @generated from field: string dbt_cloud_user_id = 11;
   */
  dbtCloudUserId: string;
};

/**
 * Describes the message v1.public.common.vortex_telemetry_contexts.VortexTelemetryDbtCloudContext.
 * Use `create(VortexTelemetryDbtCloudContextSchema)` to create a new message.
 */
export const VortexTelemetryDbtCloudContextSchema: GenMessage<VortexTelemetryDbtCloudContext> = /*@__PURE__*/
  messageDesc(file_dbtlabs_proto_public_v1_common_vortex_telemetry_contexts, 0);

/**
 * VortexTelemetryCommonContext is the standard context that must be included in all
 * vortex-enabled events as a field named common_context.
 * It provides a consistent way to identify the account, project,
 * environment, and user across all telemetry events, enabling reliable dashboards
 * and incident investigation. Fields may be empty when they are not applicable (e.g.
 * environment_id for Fusion events that have no dbt platform environment association).
 *
 * @generated from message v1.public.common.vortex_telemetry_contexts.VortexTelemetryCommonContext
 */
export type VortexTelemetryCommonContext = Message<"v1.public.common.vortex_telemetry_contexts.VortexTelemetryCommonContext"> & {
  /**
   * account identifier tied to the event
   *
   * @generated from field: string account_identifier = 1;
   */
  accountIdentifier: string;

  /**
   * project id tied to the event
   *
   * @generated from field: string project_id = 2;
   */
  projectId: string;

  /**
   * dbt Cloud environment ID
   *
   * @generated from field: string environment_id = 3;
   */
  environmentId: string;

  /**
   * user identifier tied to the event
   *
   * @generated from field: string user_id = 4;
   */
  userId: string;
};

/**
 * Describes the message v1.public.common.vortex_telemetry_contexts.VortexTelemetryCommonContext.
 * Use `create(VortexTelemetryCommonContextSchema)` to create a new message.
 */
export const VortexTelemetryCommonContextSchema: GenMessage<VortexTelemetryCommonContext> = /*@__PURE__*/
  messageDesc(file_dbtlabs_proto_public_v1_common_vortex_telemetry_contexts, 1);

