// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file dbtlabs/proto/public/v1/events/fusion/update/update.proto (package v1.public.events.fusion.update, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file dbtlabs/proto/public/v1/events/fusion/update/update.proto.
 */
export const file_dbtlabs_proto_public_v1_events_fusion_update_update: GenFile = /*@__PURE__*/
  fileDesc("CjlkYnRsYWJzL3Byb3RvL3B1YmxpYy92MS9ldmVudHMvZnVzaW9uL3VwZGF0ZS91cGRhdGUucHJvdG8SHnYxLnB1YmxpYy5ldmVudHMuZnVzaW9uLnVwZGF0ZSJVCg1QYWNrYWdlVXBkYXRlEg8KB3ZlcnNpb24YASABKAkSDwoHcGFja2FnZRgCIAEoCRIVCghleGVfcGF0aBgDIAEoCUgAiAEBQgsKCV9leGVfcGF0aEJBWj9naXRodWIuY29tL2RidC1sYWJzL3Byb3RvLWdvbGFuZy92MS9wdWJsaWMvZXZlbnRzL2Z1c2lvbi91cGRhdGViBnByb3RvMw");

/**
 * Self update attempt event.
 *
 * @generated from message v1.public.events.fusion.update.PackageUpdate
 */
export type PackageUpdate = Message<"v1.public.events.fusion.update.PackageUpdate"> & {
  /**
   * Update dbt to this version (e.g. 1.2.3) [default: latest version]
   *
   * @generated from field: string version = 1;
   */
  version: string;

  /**
   * Package to update (e.g. dbt) [default: dbt]
   *
   * @generated from field: string package = 2;
   */
  package: string;

  /**
   * The discovered path to the dbt executable
   *
   * @generated from field: optional string exe_path = 3;
   */
  exePath?: string;
};

/**
 * Describes the message v1.public.events.fusion.update.PackageUpdate.
 * Use `create(PackageUpdateSchema)` to create a new message.
 */
export const PackageUpdateSchema: GenMessage<PackageUpdate> = /*@__PURE__*/
  messageDesc(file_dbtlabs_proto_public_v1_events_fusion_update_update, 0);

