use std::collections::HashSet;

use dbt_adapter_core::{AdapterType, quote_char};
use once_cell::sync::Lazy;

pub fn format_ident(id: &str, adapter: AdapterType) -> String {
    if !need_quotes(id, adapter) {
        return id.to_string();
    }
    // Fabric/T-SQL delimits identifiers with brackets, not a symmetric quote
    // char. Everything else defers to `quote_char`, the single source of truth
    // for the dialect's identifier delimiter (backtick for BigQuery/Databricks/
    // Spark/ClickHouse, double quote otherwise).
    if adapter == AdapterType::Fabric {
        return format!("[{id}]");
    }
    let quote = quote_char(adapter);
    format!("{quote}{id}{quote}")
}

pub fn need_quotes(id: &str, adapter: AdapterType) -> bool {
    if id.is_empty() {
        return true;
    }

    let mut chars = id.chars();

    // First character rules
    let first_char = chars.next().unwrap();
    let valid_start = match adapter {
        AdapterType::Fabric => {
            first_char == '_'
                || first_char == '@'
                || first_char == '#'
                || first_char.is_ascii_alphabetic()
        }
        _ => first_char == '_' || first_char.is_ascii_alphabetic(),
    };

    if !valid_start {
        return true;
    }

    // Remaining characters
    if chars.any(|c| !is_valid_identifier_char(adapter, c)) {
        return true;
    }

    // Reserved keywords (simple baseline)
    let reserved = reserved_keywords(adapter);
    if reserved.contains(&id.to_ascii_uppercase().as_str()) {
        return true;
    }

    // Optional: T-SQL / Fabric identifier length limit
    if matches!(adapter, AdapterType::Fabric) && id.len() > 128 {
        return true;
    }

    // Snowflake normalizes unquoted identifiers to uppercase, so any lowercase
    // letter forces quoting to preserve case.
    if adapter == AdapterType::Snowflake && id.chars().any(|c| c.is_ascii_lowercase()) {
        return true;
    }

    false
}

fn is_valid_identifier_char(adapter: AdapterType, c: char) -> bool {
    match adapter {
        AdapterType::Fabric => c.is_alphanumeric() || c == '_',
        _ => c.is_alphanumeric() || c == '_',
    }
}

static EMPTY_KEYWORDS: Lazy<HashSet<&'static str>> = Lazy::new(HashSet::new);

pub fn reserved_keywords(adapter: AdapterType) -> &'static HashSet<&'static str> {
    match adapter {
        AdapterType::Fabric => &FABRIC_KEYWORDS,
        AdapterType::Exasol => &EXASOL_KEYWORDS,
        // For other adapters the proprietary TypeOpsImpl handles keyword checks via sdf-frontend;
        // the source-available fallback uses an empty set.
        _ => &EMPTY_KEYWORDS,
    }
}

// Exasol reserved words, extracted from SYS.EXA_SQL_KEYWORDS WHERE RESERVED
// on Exasol 8. Unquoted identifiers matching these fail to parse, so they
// force quoting.
static EXASOL_KEYWORDS: Lazy<HashSet<&'static str>> =
    Lazy::new(|| HashSet::from(EXASOL_KEYWORDS_ARRAY));

//TODO: revisit after Dialect is added for TSQL
static FABRIC_KEYWORDS: Lazy<HashSet<&'static str>> = Lazy::new(|| {
    HashSet::from([
        "ADD",
        "EXTERNAL",
        "PROCEDURE",
        "ALL",
        "FETCH",
        "PUBLIC",
        "ALTER",
        "FILE",
        "RAISERROR",
        "AND",
        "FILLFACTOR",
        "READ",
        "ANY",
        "FOR",
        "READTEXT",
        "AS",
        "FOREIGN",
        "RECONFIGURE",
        "ASC",
        "FREETEXT",
        "REFERENCES",
        "AUTHORIZATION",
        "FREETEXTTABLE",
        "REPLICATION",
        "BACKUP",
        "FROM",
        "RESTORE",
        "BEGIN",
        "FULL",
        "RESTRICT",
        "BETWEEN",
        "FUNCTION",
        "RETURN",
        "BREAK",
        "GOTO",
        "REVERT",
        "BROWSE",
        "GRANT",
        "REVOKE",
        "BULK",
        "GROUP",
        "RIGHT",
        "BY",
        "HAVING",
        "ROLLBACK",
        "CASCADE",
        "HOLDLOCK",
        "ROWCOUNT",
        "CASE",
        "IDENTITY",
        "ROWGUIDCOL",
        "CHECK",
        "IDENTITY_INSERT",
        "RULE",
        "CHECKPOINT",
        "IDENTITYCOL",
        "SAVE",
        "CLOSE",
        "IF",
        "SCHEMA",
        "CLUSTERED",
        "IN",
        "SECURITYAUDIT",
        "COALESCE",
        "INDEX",
        "SELECT",
        "COLLATE",
        "INNER",
        "SEMANTICKEYPHRASETABLE",
        "COLUMN",
        "INSERT",
        "SEMANTICSIMILARITYDETAILSTABLE",
        "COMMIT",
        "INTERSECT",
        "SEMANTICSIMILARITYTABLE",
        "COMPUTE",
        "INTO",
        "SESSION_USER",
        "CONSTRAINT",
        "IS",
        "SET",
        "CONTAINS",
        "JOIN",
        "SETUSER",
        "CONTAINSTABLE",
        "KEY",
        "SHUTDOWN",
        "CONTINUE",
        "KILL",
        "SOME",
        "CONVERT",
        "LEFT",
        "STATISTICS",
        "CREATE",
        "LIKE",
        "SYSTEM_USER",
        "CROSS",
        "LINENO",
        "TABLE",
        "CURRENT",
        "LOAD",
        "TABLESAMPLE",
        "CURRENT_DATE",
        "MERGE",
        "TEXTSIZE",
        "CURRENT_TIME",
        "NATIONAL",
        "THEN",
        "CURRENT_TIMESTAMP",
        "NOCHECK",
        "TO",
        "CURRENT_USER",
        "NONCLUSTERED",
        "TOP",
        "CURSOR",
        "NOT",
        "TRAN",
        "DATABASE",
        "NULL",
        "TRANSACTION",
        "DBCC",
        "NULLIF",
        "TRIGGER",
        "DEALLOCATE",
        "OF",
        "TRUNCATE",
        "DECLARE",
        "OFF",
        "TRY_CONVERT",
        "DEFAULT",
        "OFFSETS",
        "TSEQUAL",
        "DELETE",
        "ON",
        "UNION",
        "DENY",
        "OPEN",
        "UNIQUE",
        "DESC",
        "OPENDATASOURCE",
        "UNPIVOT",
        "DISK",
        "OPENQUERY",
        "UPDATE",
        "DISTINCT",
        "OPENROWSET",
        "UPDATETEXT",
        "DISTRIBUTED",
        "OPENXML",
        "USE",
        "DOUBLE",
        "OPTION",
        "USER",
        "DROP",
        "OR",
        "VALUES",
        "DUMP",
        "ORDER",
        "VARYING",
        "ELSE",
        "OUTER",
        "VIEW",
        "END",
        "OVER",
        "WAITFOR",
        "ERRLVL",
        "PERCENT",
        "WHEN",
        "ESCAPE",
        "PIVOT",
        "WHERE",
        "EXCEPT",
        "PLAN",
        "WHILE",
        "EXEC",
        "PRECISION",
        "WITH",
        "EXECUTE",
        "PRIMARY",
        "WITHIN GROUP",
        "EXISTS",
        "PRINT",
        "WRITETEXT",
        "EXIT",
        "PROC",
        "LABEL", // Synapse-exclusive
        // ISO / ODBC reserved keywords
        "ABSOLUTE",
        "EXECUTE",
        "OVERLAPS",
        "ACTION",
        "PAD",
        "ADA",
        "PARTIAL",
        "PASCAL",
        "EXTRACT",
        "POSITION",
        "ALLOCATE",
        "FALSE",
        "PRECISION",
        "FIRST",
        "PRESERVE",
        "FLOAT",
        "PRIOR",
        "ARE",
        "FOR",
        "PRIVILEGES",
        "ASSERTION",
        "FOUND",
        "PUBLIC",
        "AT",
        "FROM",
        "READ",
        "AUTHORIZATION",
        "FULL",
        "REAL",
        "AVG",
        "GET",
        "REFERENCES",
        "BEGIN",
        "GLOBAL",
        "RELATIVE",
        "BETWEEN",
        "GO",
        "RESTRICT",
        "BIT",
        "GOTO",
        "REVOKE",
        "BIT_LENGTH",
        "GRANT",
        "RIGHT",
        "BOTH",
        "GROUP",
        "ROLLBACK",
        "BY",
        "HAVING",
        "ROWS",
        "CASCADE",
        "HOUR",
        "SCHEMA",
        "CASCADED",
        "IDENTITY",
        "SCROLL",
        "CASE",
        "IMMEDIATE",
        "SECOND",
        "CAST",
        "IN",
        "SECTION",
        "CATALOG",
        "INCLUDE",
        "SELECT",
        "CHAR",
        "INDEX",
        "SESSION",
        "CHAR_LENGTH",
        "INDICATOR",
        "SESSION_USER",
        "CHARACTER",
        "INITIALLY",
        "SET",
        "CHARACTER_LENGTH",
        "INNER",
        "SIZE",
        "CHECK",
        "INPUT",
        "SMALLINT",
        "CLOSE",
        "INSENSITIVE",
        "SOME",
        "COALESCE",
        "INSERT",
        "SPACE",
        "COLLATE",
        "INT",
        "SQL",
        "COLLATION",
        "INTEGER",
        "SQLCA",
        "COLUMN",
        "INTERSECT",
        "SQLCODE",
        "COMMIT",
        "INTERVAL",
        "SQLERROR",
        "CONNECT",
        "INTO",
        "SQLSTATE",
        "CONNECTION",
        "IS",
        "SQLWARNING",
        "CONSTRAINT",
        "ISOLATION",
        "SUBSTRING",
        "CONSTRAINTS",
        "JOIN",
        "SUM",
        "CONTINUE",
        "KEY",
        "SYSTEM_USER",
        "CONVERT",
        "LANGUAGE",
        "TABLE",
        "CORRESPONDING",
        "LAST",
        "TEMPORARY",
        "COUNT",
        "LEADING",
        "THEN",
        "CREATE",
        "LEFT",
        "TIME",
        "CROSS",
        "LEVEL",
        "TIMESTAMP",
        "CURRENT",
        "LIKE",
        "TIMEZONE_HOUR",
        "CURRENT_DATE",
        "LOCAL",
        "TIMEZONE_MINUTE",
        "CURRENT_TIME",
        "LOWER",
        "TO",
        "CURRENT_TIMESTAMP",
        "MATCH",
        "TRAILING",
        "CURRENT_USER",
        "MAX",
        "TRANSACTION",
        "CURSOR",
        "MIN",
        "TRANSLATE",
        "DATE",
        "MINUTE",
        "TRANSLATION",
        "DAY",
        "MODULE",
        "TRIM",
        "DEALLOCATE",
        "MONTH",
        "TRUE",
        "DEC",
        "NAMES",
        "UNION",
        "DECIMAL",
        "NATIONAL",
        "UNIQUE",
        "DECLARE",
        "NATURAL",
        "UNKNOWN",
        "DEFAULT",
        "NCHAR",
        "UPDATE",
        "DEFERRABLE",
        "NEXT",
        "UPPER",
        "DEFERRED",
        "NO",
        "USAGE",
        "DELETE",
        "NONE",
        "USER",
        "DESC",
        "NOT",
        "USING",
        "DESCRIBE",
        "NULL",
        "VALUE",
        "DESCRIPTOR",
        "NULLIF",
        "VALUES",
        "DIAGNOSTICS",
        "NUMERIC",
        "VARCHAR",
        "DISCONNECT",
        "OCTET_LENGTH",
        "VARYING",
        "DISTINCT",
        "OF",
        "VIEW",
        "DOMAIN",
        "ON",
        "WHEN",
        "DOUBLE",
        "ONLY",
        "WHENEVER",
        "DROP",
        "OPEN",
        "WHERE",
        "ELSE",
        "OPTION",
        "WITH",
        "END",
        "OR",
        "WORK",
        "END-EXEC",
        "ORDER",
        "WRITE",
        "ESCAPE",
        "OUTER",
        "YEAR",
        "EXCEPT",
        "OUTPUT",
        "ZONE",
    ])
});

const EXASOL_KEYWORDS_ARRAY: [&str; 468] = [
    "ABSOLUTE",
    "ACTION",
    "ADD",
    "AFTER",
    "ALL",
    "ALLOCATE",
    "ALTER",
    "AND",
    "ANY",
    "APPEND",
    "ARE",
    "ARRAY",
    "AS",
    "ASC",
    "ASENSITIVE",
    "ASSERTION",
    "AT",
    "ATTRIBUTE",
    "AUTHID",
    "AUTHORIZATION",
    "BEFORE",
    "BEGIN",
    "BETWEEN",
    "BIGINT",
    "BINARY",
    "BIT",
    "BLOB",
    "BLOCKED",
    "BOOL",
    "BOOLEAN",
    "BOTH",
    "BY",
    "BYTE",
    "CALL",
    "CALLED",
    "CARDINALITY",
    "CASCADE",
    "CASCADED",
    "CASE",
    "CASESPECIFIC",
    "CAST",
    "CATALOG",
    "CHAIN",
    "CHAR",
    "CHARACTER",
    "CHARACTERISTICS",
    "CHARACTER_SET_CATALOG",
    "CHARACTER_SET_NAME",
    "CHARACTER_SET_SCHEMA",
    "CHECK",
    "CHECKED",
    "CLOB",
    "CLOSE",
    "COALESCE",
    "COLLATE",
    "COLLATION",
    "COLLATION_CATALOG",
    "COLLATION_NAME",
    "COLLATION_SCHEMA",
    "COLUMN",
    "COMMIT",
    "CONDITION",
    "CONNECTION",
    "CONNECT_BY_ISCYCLE",
    "CONNECT_BY_ISLEAF",
    "CONNECT_BY_ROOT",
    "CONSTANT",
    "CONSTRAINT",
    "CONSTRAINTS",
    "CONSTRAINT_STATE_DEFAULT",
    "CONSTRUCTOR",
    "CONTAINS",
    "CONTINUE",
    "CONTROL",
    "CONVERT",
    "CORRESPONDING",
    "CREATE",
    "CS",
    "CSV",
    "CUBE",
    "CURRENT",
    "CURRENT_CLUSTER",
    "CURRENT_CLUSTER_UID",
    "CURRENT_DATE",
    "CURRENT_PATH",
    "CURRENT_ROLE",
    "CURRENT_SCHEMA",
    "CURRENT_SESSION",
    "CURRENT_STATEMENT",
    "CURRENT_TIME",
    "CURRENT_TIMESTAMP",
    "CURRENT_USER",
    "CURSOR",
    "CYCLE",
    "DATA",
    "DATALINK",
    "DATE",
    "DATETIME_INTERVAL_CODE",
    "DATETIME_INTERVAL_PRECISION",
    "DAY",
    "DBTIMEZONE",
    "DEALLOCATE",
    "DEC",
    "DECIMAL",
    "DECLARE",
    "DEFAULT",
    "DEFAULT_LIKE_ESCAPE_CHARACTER",
    "DEFERRABLE",
    "DEFERRED",
    "DEFINED",
    "DEFINER",
    "DELETE",
    "DEREF",
    "DERIVED",
    "DESC",
    "DESCRIBE",
    "DESCRIPTOR",
    "DETERMINISTIC",
    "DISABLE",
    "DISABLED",
    "DISCONNECT",
    "DISPATCH",
    "DISTINCT",
    "DLURLCOMPLETE",
    "DLURLPATH",
    "DLURLPATHONLY",
    "DLURLSCHEME",
    "DLURLSERVER",
    "DLVALUE",
    "DO",
    "DOMAIN",
    "DOUBLE",
    "DROP",
    "DYNAMIC",
    "DYNAMIC_FUNCTION",
    "DYNAMIC_FUNCTION_CODE",
    "EACH",
    "ELSE",
    "ELSEIF",
    "ELSIF",
    "EMITS",
    "ENABLE",
    "ENABLED",
    "END",
    "END-EXEC",
    "ENDIF",
    "ENFORCE",
    "EQUALS",
    "ERRORS",
    "ESCAPE",
    "EXCEPT",
    "EXCEPTION",
    "EXEC",
    "EXECUTE",
    "EXISTS",
    "EXIT",
    "EXPORT",
    "EXTERNAL",
    "EXTRACT",
    "FALSE",
    "FBV",
    "FETCH",
    "FILE",
    "FINAL",
    "FIRST",
    "FLOAT",
    "FOLLOWING",
    "FOR",
    "FORALL",
    "FORCE",
    "FORMAT",
    "FOUND",
    "FREE",
    "FROM",
    "FS",
    "FULL",
    "FUNCTION",
    "GENERAL",
    "GENERATED",
    "GEOMETRY",
    "GET",
    "GLOBAL",
    "GO",
    "GOTO",
    "GRANT",
    "GRANTED",
    "GROUP",
    "GROUPING",
    "GROUPS",
    "GROUP_CONCAT",
    "HASHTYPE",
    "HASHTYPE_FORMAT",
    "HAVING",
    "HIGH",
    "HOLD",
    "HOUR",
    "IDENTITY",
    "IF",
    "IFNULL",
    "IMMEDIATE",
    "IMPERSONATE",
    "IMPLEMENTATION",
    "IMPORT",
    "IN",
    "INDEX",
    "INDICATOR",
    "INNER",
    "INOUT",
    "INPUT",
    "INSENSITIVE",
    "INSERT",
    "INSTANCE",
    "INSTANTIABLE",
    "INT",
    "INTEGER",
    "INTEGRITY",
    "INTERSECT",
    "INTERVAL",
    "INTO",
    "INVERSE",
    "INVOKER",
    "IS",
    "ITERATE",
    "JOIN",
    "KEY_MEMBER",
    "KEY_TYPE",
    "LARGE",
    "LAST",
    "LATERAL",
    "LDAP",
    "LEADING",
    "LEAVE",
    "LEFT",
    "LEVEL",
    "LIKE",
    "LIMIT",
    "LISTAGG",
    "LOCAL",
    "LOCALTIME",
    "LOCALTIMESTAMP",
    "LOCATOR",
    "LOG",
    "LONGVARCHAR",
    "LOOP",
    "LOW",
    "MAP",
    "MATCH",
    "MATCHED",
    "MERGE",
    "METHOD",
    "MINUS",
    "MINUTE",
    "MOD",
    "MODIFIES",
    "MODIFY",
    "MODULE",
    "MONTH",
    "NAMES",
    "NATIONAL",
    "NATURAL",
    "NCHAR",
    "NCLOB",
    "NEW",
    "NEXT",
    "NLS_DATE_FORMAT",
    "NLS_DATE_LANGUAGE",
    "NLS_FIRST_DAY_OF_WEEK",
    "NLS_NUMERIC_CHARACTERS",
    "NLS_TIMESTAMP_FORMAT",
    "NO",
    "NOCYCLE",
    "NOLOGGING",
    "NONE",
    "NOT",
    "NULL",
    "NULLIF",
    "NUMBER",
    "NUMERIC",
    "NVARCHAR",
    "NVARCHAR2",
    "OBJECT",
    "OF",
    "OFF",
    "OLD",
    "ON",
    "ONLY",
    "OPEN",
    "OPTION",
    "OPTIONS",
    "OR",
    "ORDER",
    "ORDERING",
    "ORDINALITY",
    "OTHERS",
    "OUT",
    "OUTER",
    "OUTPUT",
    "OVER",
    "OVERLAPS",
    "OVERLAY",
    "OVERRIDING",
    "PAD",
    "PARALLEL_ENABLE",
    "PARAMETER",
    "PARAMETER_SPECIFIC_CATALOG",
    "PARAMETER_SPECIFIC_NAME",
    "PARAMETER_SPECIFIC_SCHEMA",
    "PARQUET",
    "PARTIAL",
    "PATH",
    "PERMISSION",
    "PLACING",
    "PLUS",
    "POSITION",
    "PRECEDING",
    "PREFERRING",
    "PREPARE",
    "PRESERVE",
    "PRIOR",
    "PRIVILEGES",
    "PROCEDURE",
    "PROFILE",
    "QUALIFY",
    "RANDOM",
    "RANGE",
    "READ",
    "READS",
    "REAL",
    "RECOVERY",
    "RECURSIVE",
    "REF",
    "REFERENCES",
    "REFERENCING",
    "REFRESH",
    "REGEXP_LIKE",
    "RELATIVE",
    "RELEASE",
    "RENAME",
    "REPEAT",
    "REPLACE",
    "RESTORE",
    "RESTRICT",
    "RESULT",
    "RETURN",
    "RETURNED_LENGTH",
    "RETURNED_OCTET_LENGTH",
    "RETURNS",
    "REVOKE",
    "RIGHT",
    "ROLLBACK",
    "ROLLUP",
    "ROUTINE",
    "ROW",
    "ROWS",
    "ROWTYPE",
    "SAVEPOINT",
    "SCHEMA",
    "SCOPE",
    "SCOPE_USER",
    "SCRIPT",
    "SCROLL",
    "SEARCH",
    "SECOND",
    "SECTION",
    "SECURITY",
    "SELECT",
    "SELECTIVE",
    "SELF",
    "SENSITIVE",
    "SEPARATOR",
    "SEQUENCE",
    "SESSION",
    "SESSIONTIMEZONE",
    "SESSION_USER",
    "SET",
    "SETS",
    "SHORTINT",
    "SIMILAR",
    "SMALLINT",
    "SOME",
    "SOURCE",
    "SPACE",
    "SPECIFIC",
    "SPECIFICTYPE",
    "SQL",
    "SQLEXCEPTION",
    "SQLSTATE",
    "SQLWARNING",
    "SQL_BIGINT",
    "SQL_BIT",
    "SQL_CHAR",
    "SQL_DATE",
    "SQL_DECIMAL",
    "SQL_DOUBLE",
    "SQL_FLOAT",
    "SQL_INTEGER",
    "SQL_LONGVARCHAR",
    "SQL_NUMERIC",
    "SQL_PREPROCESSOR_SCRIPT",
    "SQL_REAL",
    "SQL_SMALLINT",
    "SQL_TIMESTAMP",
    "SQL_TINYINT",
    "SQL_TYPE_DATE",
    "SQL_TYPE_TIMESTAMP",
    "SQL_VARCHAR",
    "START",
    "STATE",
    "STATEMENT",
    "STATIC",
    "STRUCTURE",
    "STYLE",
    "SUBSTRING",
    "SUBTYPE",
    "SYSDATE",
    "SYSTEM",
    "SYSTEM_USER",
    "SYSTIMESTAMP",
    "TABLE",
    "TEMPORARY",
    "TEXT",
    "THEN",
    "TIME",
    "TIMESTAMP",
    "TIMEZONE_HOUR",
    "TIMEZONE_MINUTE",
    "TINYINT",
    "TO",
    "TRAILING",
    "TRANSACTION",
    "TRANSFORM",
    "TRANSFORMS",
    "TRANSLATION",
    "TREAT",
    "TRIGGER",
    "TRIM",
    "TRUE",
    "TRUNCATE",
    "UNDER",
    "UNION",
    "UNIQUE",
    "UNKNOWN",
    "UNLINK",
    "UNNEST",
    "UNTIL",
    "UPDATE",
    "USAGE",
    "USER",
    "USING",
    "VALUE",
    "VALUES",
    "VARCHAR",
    "VARCHAR2",
    "VARRAY",
    "VERIFY",
    "VIEW",
    "WHEN",
    "WHENEVER",
    "WHERE",
    "WHILE",
    "WINDOW",
    "WITH",
    "WITHIN",
    "WITHOUT",
    "WORK",
    "YEAR",
    "YES",
    "ZONE",
];

#[cfg(test)]
mod tests {
    use super::*;
    use dbt_adapter_core::AdapterType;

    #[test]
    fn test_format_ident_unquoted() {
        let id = "my_column";
        let formatted = format_ident(id, AdapterType::Fabric);
        assert_eq!(formatted, "my_column");
    }

    #[test]
    fn test_format_ident_quoted_fabric() {
        let id = "select";
        let formatted = format_ident(id, AdapterType::Fabric);
        assert_eq!(formatted, "[select]");
    }

    #[test]
    fn test_format_ident_quoted_clickhouse_does_not_escape_backticks() {
        let id = "a`b";
        let formatted = format_ident(id, AdapterType::ClickHouse);
        assert_eq!(formatted, "`a`b`");
    }

    #[test]
    fn test_format_ident_quoted_bigquery_uses_backticks() {
        // Regression for dbt-core#15561: BigQuery project ids with dashes must be
        // backtick-quoted, matching `quote_char`, not double-quoted.
        assert_eq!(
            format_ident("my-gcp-project", AdapterType::Bigquery),
            "`my-gcp-project`"
        );
    }

    #[test]
    fn test_format_ident_quoted_backtick_dialects() {
        for adapter in [AdapterType::Databricks, AdapterType::Spark] {
            assert_eq!(format_ident("a-b", adapter), "`a-b`");
        }
    }

    #[test]
    fn test_format_ident_quoted_default() {
        // Non-Fabric/ClickHouse adapters use an empty keyword baseline, so reserved
        // words are not detected and the identifier comes back unquoted.
        let id = "select";
        assert_eq!(format_ident(id, AdapterType::Postgres), "select");
    }

    #[test]
    fn test_need_quotes_empty() {
        assert!(need_quotes("", AdapterType::Fabric));
    }

    #[test]
    fn test_need_quotes_invalid_start_char() {
        assert!(need_quotes("1abc", AdapterType::Fabric));
        assert!(!need_quotes("_abc", AdapterType::Fabric));
        assert!(!need_quotes("@abc", AdapterType::Fabric));
        assert!(!need_quotes("#abc", AdapterType::Fabric));
        assert!(need_quotes("&abc", AdapterType::Fabric));
    }

    #[test]
    fn test_need_quotes_reserved_keyword() {
        assert!(need_quotes("SELECT", AdapterType::Fabric));
        assert!(need_quotes("select", AdapterType::Fabric));
    }

    #[test]
    fn test_is_valid_identifier_char() {
        assert!(is_valid_identifier_char(AdapterType::Fabric, 'a'));
        assert!(is_valid_identifier_char(AdapterType::Fabric, 'Z'));
        assert!(is_valid_identifier_char(AdapterType::Fabric, '_'));
        assert!(!is_valid_identifier_char(AdapterType::Fabric, '-'));
    }
}
