// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file dbtlabs/proto/public/v1/events/fusion/query/query.proto (package v1.public.events.fusion.query, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { ExecutionPhase } from "../phase/phase_pb";
import { file_dbtlabs_proto_public_v1_events_fusion_phase_phase } from "../phase/phase_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file dbtlabs/proto/public/v1/events/fusion/query/query.proto.
 */
export const file_dbtlabs_proto_public_v1_events_fusion_query_query: GenFile = /*@__PURE__*/
  fileDesc("CjdkYnRsYWJzL3Byb3RvL3B1YmxpYy92MS9ldmVudHMvZnVzaW9uL3F1ZXJ5L3F1ZXJ5LnByb3RvEh12MS5wdWJsaWMuZXZlbnRzLmZ1c2lvbi5xdWVyeSL+AwoNUXVlcnlFeGVjdXRlZBILCgNzcWwYASABKAkSEAoIc3FsX2hhc2gYAiABKAkSFAoMYWRhcHRlcl90eXBlGAMgASgJEh4KEXF1ZXJ5X2Rlc2NyaXB0aW9uGAQgASgJSACIAQESFQoIcXVlcnlfaWQYBSABKAlIAYgBARIWCgl1bmlxdWVfaWQYBiABKAlIAogBARJCCg1xdWVyeV9vdXRjb21lGAcgASgOMisudjEucHVibGljLmV2ZW50cy5mdXNpb24ucXVlcnkuUXVlcnlPdXRjb21lEkEKBXBoYXNlGAggASgOMi0udjEucHVibGljLmV2ZW50cy5mdXNpb24ucGhhc2UuRXhlY3V0aW9uUGhhc2VIA4gBARIoChtxdWVyeV9lcnJvcl9hZGFwdGVyX21lc3NhZ2UYCSABKAlIBIgBARIkChdxdWVyeV9lcnJvcl92ZW5kb3JfY29kZRgKIAEoBUgFiAEBEhsKE2RidF9jb3JlX2V2ZW50X2NvZGUYCyABKAlCFAoSX3F1ZXJ5X2Rlc2NyaXB0aW9uQgsKCV9xdWVyeV9pZEIMCgpfdW5pcXVlX2lkQggKBl9waGFzZUIeChxfcXVlcnlfZXJyb3JfYWRhcHRlcl9tZXNzYWdlQhoKGF9xdWVyeV9lcnJvcl92ZW5kb3JfY29kZSJ5ChNDb25uZWN0aW9uTGltaXRXYWl0EhkKDGFjdGl2ZV9ub2RlcxgBIAEoDUgAiAEBEh8KEmFjdGl2ZV9jb25uZWN0aW9ucxgCIAEoDUgBiAEBQg8KDV9hY3RpdmVfbm9kZXNCFQoTX2FjdGl2ZV9jb25uZWN0aW9ucyJGChVBZGFwdGVyQ29ubmVjdGlvbk9wZW4SFAoMYWRhcHRlcl90eXBlGAEgASgJEhcKD2FkYXB0ZXJfYmFja2VuZBgCIAEoCSImChZBZGFwdGVyQ29ubmVjdGlvbkNsb3NlEgwKBHJlcHIYASABKAkqfQoMUXVlcnlPdXRjb21lEh0KGVFVRVJZX09VVENPTUVfVU5TUEVDSUZJRUQQABIZChVRVUVSWV9PVVRDT01FX1NVQ0NFU1MQARIXChNRVUVSWV9PVVRDT01FX0VSUk9SEAISGgoWUVVFUllfT1VUQ09NRV9DQU5DRUxFRBADQkBaPmdpdGh1Yi5jb20vZGJ0LWxhYnMvcHJvdG8tZ29sYW5nL3YxL3B1YmxpYy9ldmVudHMvZnVzaW9uL3F1ZXJ5YgZwcm90bzM", [file_dbtlabs_proto_public_v1_events_fusion_phase_phase]);

/**
 * @generated from message v1.public.events.fusion.query.QueryExecuted
 */
export type QueryExecuted = Message<"v1.public.events.fusion.query.QueryExecuted"> & {
  /**
   * Raw SQL string that was executed. May be obfuscated.
   *
   * @generated from field: string sql = 1;
   */
  sql: string;

  /**
   * Blake3, 16-bytes hash of the raw SQL string encoded as hex.
   *
   * @generated from field: string sql_hash = 2;
   */
  sqlHash: string;

  /**
   * Type of the adapter (e.g. "snowflake", "bigquery", "postgres", etc.)
   *
   * @generated from field: string adapter_type = 3;
   */
  adapterType: string;

  /**
   * Optional human-readable description of the query.
   *
   * @generated from field: optional string query_description = 4;
   */
  queryDescription?: string;

  /**
   * Database provided query ID for the executed query, if available.
   *
   * @generated from field: optional string query_id = 5;
   */
  queryId?: string;

  /**
   * unique_id of the node that generated this query. Some queries may not be associated with a single node.
   *
   * @generated from field: optional string unique_id = 6;
   */
  uniqueId?: string;

  /**
   * Outcome for this query execution.
   *
   * @generated from field: v1.public.events.fusion.query.QueryOutcome query_outcome = 7;
   */
  queryOutcome: QueryOutcome;

  /**
   * Execution phase during which this query was evaluated, if available
   *
   * @generated from field: optional v1.public.events.fusion.phase.ExecutionPhase phase = 8;
   */
  phase?: ExecutionPhase;

  /**
   * Arbitrary adapter defined error message
   *
   * @generated from field: optional string query_error_adapter_message = 9;
   */
  queryErrorAdapterMessage?: string;

  /**
   * Arbitrary adapter (vendor) defined error code
   *
   * @generated from field: optional int32 query_error_vendor_code = 10;
   */
  queryErrorVendorCode?: number;

  /**
   * Legacy dbt core event code: E016 or E017
   *
   * @generated from field: string dbt_core_event_code = 11;
   */
  dbtCoreEventCode: string;
};

/**
 * Describes the message v1.public.events.fusion.query.QueryExecuted.
 * Use `create(QueryExecutedSchema)` to create a new message.
 */
export const QueryExecutedSchema: GenMessage<QueryExecuted> = /*@__PURE__*/
  messageDesc(file_dbtlabs_proto_public_v1_events_fusion_query_query, 0);

/**
 * Time spent waiting for connection concurrency limits to allow a node to proceed.
 *
 * @generated from message v1.public.events.fusion.query.ConnectionLimitWait
 */
export type ConnectionLimitWait = Message<"v1.public.events.fusion.query.ConnectionLimitWait"> & {
  /**
   * Number of active nodes in task runner. Empty unless trace log level is set.
   *
   * @generated from field: optional uint32 active_nodes = 1;
   */
  activeNodes?: number;

  /**
   * Number of active adapter connections. Empty unless trace log level is set.
   *
   * @generated from field: optional uint32 active_connections = 2;
   */
  activeConnections?: number;
};

/**
 * Describes the message v1.public.events.fusion.query.ConnectionLimitWait.
 * Use `create(ConnectionLimitWaitSchema)` to create a new message.
 */
export const ConnectionLimitWaitSchema: GenMessage<ConnectionLimitWait> = /*@__PURE__*/
  messageDesc(file_dbtlabs_proto_public_v1_events_fusion_query_query, 1);

/**
 * Event emitted when an adapter connection is opened. Only emitted at trace log level.
 *
 * @generated from message v1.public.events.fusion.query.AdapterConnectionOpen
 */
export type AdapterConnectionOpen = Message<"v1.public.events.fusion.query.AdapterConnectionOpen"> & {
  /**
   * Adapter type name
   *
   * @generated from field: string adapter_type = 1;
   */
  adapterType: string;

  /**
   * Adapter backend (driver) name
   *
   * @generated from field: string adapter_backend = 2;
   */
  adapterBackend: string;
};

/**
 * Describes the message v1.public.events.fusion.query.AdapterConnectionOpen.
 * Use `create(AdapterConnectionOpenSchema)` to create a new message.
 */
export const AdapterConnectionOpenSchema: GenMessage<AdapterConnectionOpen> = /*@__PURE__*/
  messageDesc(file_dbtlabs_proto_public_v1_events_fusion_query_query, 2);

/**
 * Event emitted when an adapter connection is closed. Only emitted at trace log level.
 *
 * @generated from message v1.public.events.fusion.query.AdapterConnectionClose
 */
export type AdapterConnectionClose = Message<"v1.public.events.fusion.query.AdapterConnectionClose"> & {
  /**
   * Debug representation of the adapter connection being closed.
   *
   * @generated from field: string repr = 1;
   */
  repr: string;
};

/**
 * Describes the message v1.public.events.fusion.query.AdapterConnectionClose.
 * Use `create(AdapterConnectionCloseSchema)` to create a new message.
 */
export const AdapterConnectionCloseSchema: GenMessage<AdapterConnectionClose> = /*@__PURE__*/
  messageDesc(file_dbtlabs_proto_public_v1_events_fusion_query_query, 3);

/**
 * Outcome of a query execution
 *
 * @generated from enum v1.public.events.fusion.query.QueryOutcome
 */
export enum QueryOutcome {
  /**
   * Default value. Should only be set on unfinished spans
   *
   * @generated from enum value: QUERY_OUTCOME_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Successfully executed the query.
   *
   * @generated from enum value: QUERY_OUTCOME_SUCCESS = 1;
   */
  SUCCESS = 1,

  /**
   * Failed with an error type (individual errors reported as separate events).
   * If set, `node_error_type` with also be set to indicate the type of error.
   *
   * @generated from enum value: QUERY_OUTCOME_ERROR = 2;
   */
  ERROR = 2,

  /**
   * Query was canceled (e.g. user-initiated cancellation).
   *
   * @generated from enum value: QUERY_OUTCOME_CANCELED = 3;
   */
  CANCELED = 3,
}

/**
 * Describes the enum v1.public.events.fusion.query.QueryOutcome.
 */
export const QueryOutcomeSchema: GenEnum<QueryOutcome> = /*@__PURE__*/
  enumDesc(file_dbtlabs_proto_public_v1_events_fusion_query_query, 0);

