// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file dbtlabs/proto/public/v1/events/fusion/process/process.proto (package v1.public.events.fusion.process, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file dbtlabs/proto/public/v1/events/fusion/process/process.proto.
 */
export const file_dbtlabs_proto_public_v1_events_fusion_process_process: GenFile = /*@__PURE__*/
  fileDesc("CjtkYnRsYWJzL3Byb3RvL3B1YmxpYy92MS9ldmVudHMvZnVzaW9uL3Byb2Nlc3MvcHJvY2Vzcy5wcm90bxIfdjEucHVibGljLmV2ZW50cy5mdXNpb24ucHJvY2VzcyJPCgdQcm9jZXNzEg8KB3BhY2thZ2UYAyABKAkSDwoHdmVyc2lvbhgEIAEoCRIPCgdob3N0X29zGAUgASgJEhEKCWhvc3RfYXJjaBgGIAEoCUJCWkBnaXRodWIuY29tL2RidC1sYWJzL3Byb3RvLWdvbGFuZy92MS9wdWJsaWMvZXZlbnRzL2Z1c2lvbi9wcm9jZXNzYgZwcm90bzM");

/**
 * Process-wide attributes for a telemetry-emitting process.
 *
 * @generated from message v1.public.events.fusion.process.Process
 */
export type Process = Message<"v1.public.events.fusion.process.Process"> & {
  /**
   * Name of the emitting package, e.g. "dbt" or "dbt-lsp".
   *
   * @generated from field: string package = 3;
   */
  package: string;

  /**
   * Version of the emitting package, e.g. "v2.0.0".
   *
   * @generated from field: string version = 4;
   */
  version: string;

  /**
   * Host operating system, e.g. "linux", "darwin", "windows".
   *
   * @generated from field: string host_os = 5;
   */
  hostOs: string;

  /**
   * Host architecture, e.g. "x86_64", "aarch64".
   *
   * @generated from field: string host_arch = 6;
   */
  hostArch: string;
};

/**
 * Describes the message v1.public.events.fusion.process.Process.
 * Use `create(ProcessSchema)` to create a new message.
 */
export const ProcessSchema: GenMessage<Process> = /*@__PURE__*/
  messageDesc(file_dbtlabs_proto_public_v1_events_fusion_process_process, 0);

