// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file dbtlabs/proto/public/v1/events/mcp.proto (package v1.public.events.mcp, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_dbtlabs_proto_public_v1_common_vortex_options } from "../common/vortex_options_pb";
import type { VortexMessageEnrichment } from "./vortex_pb";
import { file_dbtlabs_proto_public_v1_events_vortex } from "./vortex_pb";
import type { VortexTelemetryCommonContext, VortexTelemetryDbtCloudContext } from "../common/vortex_telemetry_contexts_pb";
import { file_dbtlabs_proto_public_v1_common_vortex_telemetry_contexts } from "../common/vortex_telemetry_contexts_pb";
import { file_google_protobuf_struct } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file dbtlabs/proto/public/v1/events/mcp.proto.
 */
export const file_dbtlabs_proto_public_v1_events_mcp: GenFile = /*@__PURE__*/
  fileDesc("CihkYnRsYWJzL3Byb3RvL3B1YmxpYy92MS9ldmVudHMvbWNwLnByb3RvEhR2MS5wdWJsaWMuZXZlbnRzLm1jcCL0BwoKVG9vbENhbGxlZBI9CgplbnJpY2htZW50GAEgASgLMikudjEuZXZlbnRzLnZvcnRleC5Wb3J0ZXhNZXNzYWdlRW5yaWNobWVudBIQCghldmVudF9pZBgCIAEoCRIVCg1zdGFydF90aW1lX21zGAMgASgDEhMKC2VuZF90aW1lX21zGAQgASgDEhEKCXRvb2xfbmFtZRgFIAEoCRJCCglhcmd1bWVudHMYBiADKAsyLy52MS5wdWJsaWMuZXZlbnRzLm1jcC5Ub29sQ2FsbGVkLkFyZ3VtZW50c0VudHJ5EhUKDWVycm9yX21lc3NhZ2UYByABKAkSJAocZGJ0X2Nsb3VkX2Vudmlyb25tZW50X2lkX2RldhgIIAEoCRIlCh1kYnRfY2xvdWRfZW52aXJvbm1lbnRfaWRfcHJvZBgJIAEoCRIZChFkYnRfY2xvdWRfdXNlcl9pZBgKIAEoCRIVCg1sb2NhbF91c2VyX2lkGAsgASgJEgwKBGhvc3QYDCABKAkSIAoYbXVsdGljZWxsX2FjY291bnRfcHJlZml4GA0gASgJElcKA2N0eBgOIAEoCzJKLnYxLnB1YmxpYy5jb21tb24udm9ydGV4X3RlbGVtZXRyeV9jb250ZXh0cy5Wb3J0ZXhUZWxlbWV0cnlEYnRDbG91ZENvbnRleHQSFwoPZGJ0X21jcF92ZXJzaW9uGA8gASgJEh0KFWF1dGhlbnRpY2F0aW9uX21ldGhvZBgQIAEoCRIQCgh0cmFjZV9pZBgRIAEoCRIZChFkaXNhYmxlZF90b29sc2V0cxgSIAMoCRIWCg5kaXNhYmxlZF90b29scxgTIAMoCRISCgp1c2VyX2FnZW50GBQgASgJEhYKDmF0dHJpYnV0aW9uX2lkGBUgASgJEmAKDmNvbW1vbl9jb250ZXh0GBYgASgLMkgudjEucHVibGljLmNvbW1vbi52b3J0ZXhfdGVsZW1ldHJ5X2NvbnRleHRzLlZvcnRleFRlbGVtZXRyeUNvbW1vbkNvbnRleHQSHgoWcmVxdWVzdF90b2tlbl9lc3RpbWF0ZRgXIAEoAxIfChdyZXNwb25zZV90b2tlbl9lc3RpbWF0ZRgYIAEoAxIfChd0b2tlbl9lc3RpbWF0aW9uX21ldGhvZBgZIAEoCRIRCglsbG1fbW9kZWwYGiABKAkSGgoScmVxdWVzdF9jaGFyX2NvdW50GBsgASgDEhsKE3Jlc3BvbnNlX2NoYXJfY291bnQYHCABKAMaMAoOQXJndW1lbnRzRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgJOgI4AToI2KYdA4CnHQFCN1o1Z2l0aHViLmNvbS9kYnQtbGFicy9wcm90by1nb2xhbmcvdjEvcHVibGljL2V2ZW50cy9tY3BiBnByb3RvMw", [file_dbtlabs_proto_public_v1_common_vortex_options, file_dbtlabs_proto_public_v1_events_vortex, file_dbtlabs_proto_public_v1_common_vortex_telemetry_contexts, file_google_protobuf_struct]);

/**
 * @generated from message v1.public.events.mcp.ToolCalled
 */
export type ToolCalled = Message<"v1.public.events.mcp.ToolCalled"> & {
  /**
   * @generated from field: v1.events.vortex.VortexMessageEnrichment enrichment = 1;
   */
  enrichment?: VortexMessageEnrichment;

  /**
   * event_id is the unique identifier for this event. It is a generated UUID.
   *
   * @generated from field: string event_id = 2;
   */
  eventId: string;

  /**
   * The start of the tool call in milliseconds since the Unix epoch
   *
   * @generated from field: int64 start_time_ms = 3;
   */
  startTimeMs: bigint;

  /**
   * The end of the tool call in milliseconds since the Unix epoch
   *
   * @generated from field: int64 end_time_ms = 4;
   */
  endTimeMs: bigint;

  /**
   * The name of the tool, e.g. get_dimentions, dbt build, get_mart_models
   *
   * @generated from field: string tool_name = 5;
   */
  toolName: string;

  /**
   * The arguments supplied to the tool, e.g. a list of metrics or a dbt CLI selector
   *
   * @generated from field: map<string, string> arguments = 6;
   */
  arguments: { [key: string]: string };

  /**
   * An error message if the call fails
   *
   * @generated from field: string error_message = 7;
   */
  errorMessage: string;

  /**
   * The user can optionally set their dev environment id to use tools like the execute_sql
   *
   * @generated from field: string dbt_cloud_environment_id_dev = 8;
   */
  dbtCloudEnvironmentIdDev: string;

  /**
   * The user can optionally set their prod environment id to use tools like list_metrics
   *
   * @generated from field: string dbt_cloud_environment_id_prod = 9;
   */
  dbtCloudEnvironmentIdProd: string;

  /**
   * The user can optionally set their user id to use tools like execute_sql
   *
   * @generated from field: string dbt_cloud_user_id = 10;
   */
  dbtCloudUserId: string;

  /**
   * The user id found at ~/.dbt/.user.yml if present
   *
   * @generated from field: string local_user_id = 11;
   */
  localUserId: string;

  /**
   * The dbt Cloud host that the user configured
   *
   * @generated from field: string host = 12;
   */
  host: string;

  /**
   * The multicell account prefix that the user configured: https://docs.getdbt.com/docs/cloud/about-cloud/access-regions-ip-addresses
   *
   * @generated from field: string multicell_account_prefix = 13;
   */
  multicellAccountPrefix: string;

  /**
   * Common dbt Platform context
   *
   * @generated from field: v1.public.common.vortex_telemetry_contexts.VortexTelemetryDbtCloudContext ctx = 14;
   */
  ctx?: VortexTelemetryDbtCloudContext;

  /**
   * The version of dbt_mcp being used (e.g. 0.8.2)
   *
   * @generated from field: string dbt_mcp_version = 15;
   */
  dbtMcpVersion: string;

  /**
   * How the instance of dbt-mcp was authenticated. Only applicable to local MCP (e.g. env-vars, oauth, null)
   *
   * @generated from field: string authentication_method = 16;
   */
  authenticationMethod: string;

  /**
   * The trace that this tool call is associated with, i.e., the tools it is called with for a single user message. Only applicable to tool calls within an agent run in the dbt Platform.
   *
   * @generated from field: string trace_id = 17;
   */
  traceId: string;

  /**
   * The list of disabled toolsets from the DISABLE_* environment variables or x-dbt-disable-toolsets header.
   *
   * @generated from field: repeated string disabled_toolsets = 18;
   */
  disabledToolsets: string[];

  /**
   * This list of disabled tools from the DISABLE_TOOLS environment variable or x-dbt-disable-tools header.
   *
   * @generated from field: repeated string disabled_tools = 19;
   */
  disabledTools: string[];

  /**
   * Indicates where this request is coming from with the user_agent header. This is only relevant for remote MCP. For local MCP, the user_agent can be attained from the enrichment field.
   *
   * @generated from field: string user_agent = 20;
   */
  userAgent: string;

  /**
   * Attribution identifier for tracking. Uses the format "type__value" (e.g. "thread_id__<x-dbt-copilot-thread-id>"). Only applicable to tool calls within an agent run in the dbt Platform.
   *
   * @generated from field: string attribution_id = 21;
   */
  attributionId: string;

  /**
   * @generated from field: v1.public.common.vortex_telemetry_contexts.VortexTelemetryCommonContext common_context = 22;
   */
  commonContext?: VortexTelemetryCommonContext;

  /**
   * Estimated number of tokens in the serialized tool arguments (the tool call input).
   * Approximate: produced by a single reference tokenizer server-side, not the calling
   * client's actual tokenizer. See token_estimation_method for how it was derived.
   *
   * @generated from field: int64 request_token_estimate = 23;
   */
  requestTokenEstimate: bigint;

  /**
   * Estimated number of tokens in the serialized tool response payload (the tool call
   * output). Approximate in the same way as request_token_estimate.
   *
   * @generated from field: int64 response_token_estimate = 24;
   */
  responseTokenEstimate: bigint;

  /**
   * How the token estimates were produced, e.g. "tiktoken/o200k_base" or "char_div_4".
   * Lets consumers treat the estimates as approximate and know when the method changed.
   *
   * @generated from field: string token_estimation_method = 25;
   */
  tokenEstimationMethod: string;

  /**
   * The LLM model the calling client used, when known (e.g. "claude-sonnet-4-5"). Populated
   * for tool calls within an agent run in the dbt Platform, where the model is resolved
   * server-side. Blank for remote and local MCP, where the client's model is not known to
   * the server.
   *
   * @generated from field: string llm_model = 26;
   */
  llmModel: string;

  /**
   * Exact character count of the serialized tool arguments. Deterministic and
   * tokenizer-independent — the durable primitive behind request_token_estimate.
   *
   * @generated from field: int64 request_char_count = 27;
   */
  requestCharCount: bigint;

  /**
   * Exact character count of the serialized tool response payload. Deterministic and
   * tokenizer-independent — the durable primitive behind response_token_estimate.
   *
   * @generated from field: int64 response_char_count = 28;
   */
  responseCharCount: bigint;
};

/**
 * Describes the message v1.public.events.mcp.ToolCalled.
 * Use `create(ToolCalledSchema)` to create a new message.
 */
export const ToolCalledSchema: GenMessage<ToolCalled> = /*@__PURE__*/
  messageDesc(file_dbtlabs_proto_public_v1_events_mcp, 0);

