// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file dbtlabs/proto/public/v1/events/fusion/phase/phase.proto (package v1.public.events.fusion.phase, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file dbtlabs/proto/public/v1/events/fusion/phase/phase.proto.
 */
export const file_dbtlabs_proto_public_v1_events_fusion_phase_phase: GenFile = /*@__PURE__*/
  fileDesc("CjdkYnRsYWJzL3Byb3RvL3B1YmxpYy92MS9ldmVudHMvZnVzaW9uL3BoYXNlL3BoYXNlLnByb3RvEh12MS5wdWJsaWMuZXZlbnRzLmZ1c2lvbi5waGFzZSLtAQoNUGhhc2VFeGVjdXRlZBI8CgVwaGFzZRgBIAEoDjItLnYxLnB1YmxpYy5ldmVudHMuZnVzaW9uLnBoYXNlLkV4ZWN1dGlvblBoYXNlEh0KEG5vZGVfY291bnRfdG90YWwYAiABKARIAIgBARIfChJub2RlX2NvdW50X3NraXBwZWQYAyABKARIAYgBARIdChBub2RlX2NvdW50X2Vycm9yGAQgASgESAKIAQFCEwoRX25vZGVfY291bnRfdG90YWxCFQoTX25vZGVfY291bnRfc2tpcHBlZEITChFfbm9kZV9jb3VudF9lcnJvcir5BAoORXhlY3V0aW9uUGhhc2USHwobRVhFQ1VUSU9OX1BIQVNFX1VOU1BFQ0lGSUVEEAASGQoVRVhFQ1VUSU9OX1BIQVNFX0NMRUFOEAoSIAocRVhFQ1VUSU9OX1BIQVNFX0xPQURfUFJPSkVDVBAUEhkKFUVYRUNVVElPTl9QSEFTRV9QQVJTRRAeEhwKGEVYRUNVVElPTl9QSEFTRV9TQ0hFRFVMRRAoEhsKF0VYRUNVVElPTl9QSEFTRV9DT01QQVJFEC0SIAocRVhFQ1VUSU9OX1BIQVNFX0lOSVRfQURBUFRFUhAyEiMKH0VYRUNVVElPTl9QSEFTRV9ERUZFUl9IWURSQVRJT04QPBIkCiBFWEVDVVRJT05fUEhBU0VfU0NIRU1BX0hZRFJBVElPThBBEiQKIEVYRUNVVElPTl9QSEFTRV9UQVNLX0dSQVBIX0JVSUxEEEYSKAokRVhFQ1VUSU9OX1BIQVNFX05PREVfQ0FDSEVfSFlEUkFUSU9OEFASGgoWRVhFQ1VUSU9OX1BIQVNFX1JFTkRFUhBaEhsKF0VYRUNVVElPTl9QSEFTRV9BTkFMWVpFEGQSFwoTRVhFQ1VUSU9OX1BIQVNFX1JVThBuEiYKIkVYRUNVVElPTl9QSEFTRV9GUkVTSE5FU1NfQU5BTFlTSVMQeBIcChdFWEVDVVRJT05fUEhBU0VfTElORUFHRRCCARIaChVFWEVDVVRJT05fUEhBU0VfREVCVUcQjAESIQocRVhFQ1VUSU9OX1BIQVNFX09OX1JVTl9TVEFSVBCWARIfChpFWEVDVVRJT05fUEhBU0VfT05fUlVOX0VORBCgAUJAWj5naXRodWIuY29tL2RidC1sYWJzL3Byb3RvLWdvbGFuZy92MS9wdWJsaWMvZXZlbnRzL2Z1c2lvbi9waGFzZWIGcHJvdG8z");

/**
 * Top-level event for reporting a build phase, with optional details.
 *
 * @generated from message v1.public.events.fusion.phase.PhaseExecuted
 */
export type PhaseExecuted = Message<"v1.public.events.fusion.phase.PhaseExecuted"> & {
  /**
   * The current phase of execution.
   *
   * @generated from field: v1.public.events.fusion.phase.ExecutionPhase phase = 1;
   */
  phase: ExecutionPhase;

  /**
   * Optional count of total individual items within the phase (nodes or hooks).
   *
   * @generated from field: optional uint64 node_count_total = 2;
   */
  nodeCountTotal?: bigint;

  /**
   * Optional count of skipped items within the phase.
   * Skipped means NODE_OUTCOME_SKIPPED for node phases and HOOK_OUTCOME_SKIPPED for hook phases.
   *
   * @generated from field: optional uint64 node_count_skipped = 3;
   */
  nodeCountSkipped?: bigint;

  /**
   * Optional count of errored items within the phase.
   * Error means NODE_OUTCOME_ERROR for node phases and HOOK_OUTCOME_ERROR for hook phases.
   *
   * @generated from field: optional uint64 node_count_error = 4;
   */
  nodeCountError?: bigint;
};

/**
 * Describes the message v1.public.events.fusion.phase.PhaseExecuted.
 * Use `create(PhaseExecutedSchema)` to create a new message.
 */
export const PhaseExecutedSchema: GenMessage<PhaseExecuted> = /*@__PURE__*/
  messageDesc(file_dbtlabs_proto_public_v1_events_fusion_phase_phase, 0);

/**
 * A superset of all possible phases across all dbt commands.
 * Note that not all phases are relevant to all commands.
 *
 * @generated from enum v1.public.events.fusion.phase.ExecutionPhase
 */
export enum ExecutionPhase {
  /**
   * Do not use.
   *
   * @generated from enum value: EXECUTION_PHASE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Cleaning output folders (e.g. the target directory)
   *
   * @generated from enum value: EXECUTION_PHASE_CLEAN = 10;
   */
  CLEAN = 10,

  /**
   * dbt Project loading: analyzing dbt_project, profiles.yml and scanning files
   *
   * @generated from enum value: EXECUTION_PHASE_LOAD_PROJECT = 20;
   */
  LOAD_PROJECT = 20,

  /**
   * Parsing and macro name resolution of all dbt files
   *
   * @generated from enum value: EXECUTION_PHASE_PARSE = 30;
   */
  PARSE = 30,

  /**
   * Schedule nodes based on selection criteria and dependencies.
   *
   * @generated from enum value: EXECUTION_PHASE_SCHEDULE = 40;
   */
  SCHEDULE = 40,

  /**
   * Run dbt-compare macros against selected nodes
   *
   * @generated from enum value: EXECUTION_PHASE_COMPARE = 45;
   */
  COMPARE = 45,

  /**
   * Initializing the adapter (warehouse connection and configuration)
   *
   * @generated from enum value: EXECUTION_PHASE_INIT_ADAPTER = 50;
   */
  INIT_ADAPTER = 50,

  /**
   * Handling deferral. Fetching state source schemas from remote, hydrating relation, and schema cache
   *
   * @generated from enum value: EXECUTION_PHASE_DEFER_HYDRATION = 60;
   */
  DEFER_HYDRATION = 60,

  /**
   * Hydration of schemas for static analysis
   *
   * @generated from enum value: EXECUTION_PHASE_SCHEMA_HYDRATION = 65;
   */
  SCHEMA_HYDRATION = 65,

  /**
   * Building the task graph from the schedule
   *
   * @generated from enum value: EXECUTION_PHASE_TASK_GRAPH_BUILD = 70;
   */
  TASK_GRAPH_BUILD = 70,

  /**
   * Hydration of cached models, seeds, snapshots and sources
   *
   * @generated from enum value: EXECUTION_PHASE_NODE_CACHE_HYDRATION = 80;
   */
  NODE_CACHE_HYDRATION = 80,

  /**
   * Render SQL (also called `compile` in dbt core)
   *
   * @generated from enum value: EXECUTION_PHASE_RENDER = 90;
   */
  RENDER = 90,

  /**
   * SQL static analysis
   *
   * @generated from enum value: EXECUTION_PHASE_ANALYZE = 100;
   */
  ANALYZE = 100,

  /**
   * Execution against the target database
   *
   * @generated from enum value: EXECUTION_PHASE_RUN = 110;
   */
  RUN = 110,

  /**
   * Freshness analysis of sources and models
   *
   * @generated from enum value: EXECUTION_PHASE_FRESHNESS_ANALYSIS = 120;
   */
  FRESHNESS_ANALYSIS = 120,

  /**
   * Analysis of individual node lineages
   *
   * @generated from enum value: EXECUTION_PHASE_LINEAGE = 130;
   */
  LINEAGE = 130,

  /**
   * Debugging connection correctness and availability to the warehouse
   *
   * @generated from enum value: EXECUTION_PHASE_DEBUG = 140;
   */
  DEBUG = 140,

  /**
   * Executing on-run-start hooks at the start of supported dbt commands
   *
   * @generated from enum value: EXECUTION_PHASE_ON_RUN_START = 150;
   */
  ON_RUN_START = 150,

  /**
   * Executing on-run-end hooks at the end of supported dbt commands
   *
   * @generated from enum value: EXECUTION_PHASE_ON_RUN_END = 160;
   */
  ON_RUN_END = 160,
}

/**
 * Describes the enum v1.public.events.fusion.phase.ExecutionPhase.
 */
export const ExecutionPhaseSchema: GenEnum<ExecutionPhase> = /*@__PURE__*/
  enumDesc(file_dbtlabs_proto_public_v1_events_fusion_phase_phase, 0);

