import sys

def format_contributors(version):
    """
    Takes in a version matching a markdown file generated by changie in the .changes directory.
    Grabs the contributor info at the end of each change line, pulls it off and puts it all at the
    bottom of this bacth of changes in a contributing section.
    """
    fp = f'../.changes/{version}.md'
    separator = 'ContributorData '
    change_indicator = "*"

    cont_list = {}
    core_team = ['core-team']

    new_file_contents = ""

    with open(fp, "r+") as f:
        string_list = f.readlines()
        for line in string_list:
            if line[0] == change_indicator:
                a, b = line.split(separator)
                user, issue = b.split(" ")
                if user not in core_team:
                    if user in cont_list:
                        cont_list[user].append(issue.strip('\n'))
                    else:
                        cont_list[user] = [issue.strip('\n')]
                line = f"{a}\n"
            new_file_contents += line

        f.seek(0)
        f.write(new_file_contents)
        f.write("\nContributors:\n")
        for key, value in cont_list.items():
            user = f"[@{key}](https://github.com/{key})"
            issues = ""
            for i in value:
                issues += f"[#{i}](https://github.com/dbt-labs/dbt-core/pull/{i})"
            entry = f"{user} {issues}\n"
            f.write(entry)




def main():
    try:
        version = sys.argv[1]
    except IndexError:
        raise Exception('A version is required in the format 1.0.3')

    format_contributors(version)
    print(f"Contributing section added to .changes/{version}.md.")



if __name__ == '__main__':
    main()