// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file dbtlabs/proto/public/v1/events/fusion/dev/dev.proto (package v1.public.events.fusion.dev, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file dbtlabs/proto/public/v1/events/fusion/dev/dev.proto.
 */
export const file_dbtlabs_proto_public_v1_events_fusion_dev_dev: GenFile = /*@__PURE__*/
  fileDesc("CjNkYnRsYWJzL3Byb3RvL3B1YmxpYy92MS9ldmVudHMvZnVzaW9uL2Rldi9kZXYucHJvdG8SG3YxLnB1YmxpYy5ldmVudHMuZnVzaW9uLmRldiJbCgpEZWJ1Z1ZhbHVlEhEKB2Zsb2F0NjQYASABKAFIABIOCgRib29sGAQgASgISAASEAoGc3RyaW5nGAUgASgJSAASDwoFYnl0ZXMYBiABKAxIAEIHCgV2YWx1ZSLqAQoJQ2FsbFRyYWNlEgwKBG5hbWUYASABKAkSEQoEZmlsZRgCIAEoCUgAiAEBEhEKBGxpbmUYAyABKA1IAYgBARJACgVleHRyYRgEIAMoCzIxLnYxLnB1YmxpYy5ldmVudHMuZnVzaW9uLmRldi5DYWxsVHJhY2UuRXh0cmFFbnRyeRpVCgpFeHRyYUVudHJ5EgsKA2tleRgBIAEoCRI2CgV2YWx1ZRgCIAEoCzInLnYxLnB1YmxpYy5ldmVudHMuZnVzaW9uLmRldi5EZWJ1Z1ZhbHVlOgI4AUIHCgVfZmlsZUIHCgVfbGluZSIzCgdVbmtub3duEgwKBG5hbWUYASABKAkSDAoEZmlsZRgCIAEoCRIMCgRsaW5lGAMgASgNQj5aPGdpdGh1Yi5jb20vZGJ0LWxhYnMvcHJvdG8tZ29sYW5nL3YxL3B1YmxpYy9ldmVudHMvZnVzaW9uL2RldmIGcHJvdG8z");

/**
 * General debug value holder for developer spans.
 *
 * @generated from message v1.public.events.fusion.dev.DebugValue
 */
export type DebugValue = Message<"v1.public.events.fusion.dev.DebugValue"> & {
  /**
   * @generated from oneof v1.public.events.fusion.dev.DebugValue.value
   */
  value: {
    /**
     * @generated from field: double float64 = 1;
     */
    value: number;
    case: "float64";
  } | {
    /**
     * @generated from field: bool bool = 4;
     */
    value: boolean;
    case: "bool";
  } | {
    /**
     * @generated from field: string string = 5;
     */
    value: string;
    case: "string";
  } | {
    /**
     * @generated from field: bytes bytes = 6;
     */
    value: Uint8Array;
    case: "bytes";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message v1.public.events.fusion.dev.DebugValue.
 * Use `create(DebugValueSchema)` to create a new message.
 */
export const DebugValueSchema: GenMessage<DebugValue> = /*@__PURE__*/
  messageDesc(file_dbtlabs_proto_public_v1_events_fusion_dev_dev, 0);

/**
 * Special event emitted only at TRACE level, and disabled by default.
 * Used for troubleshooting complex bugs in Fusion itself.
 *
 * @generated from message v1.public.events.fusion.dev.CallTrace
 */
export type CallTrace = Message<"v1.public.events.fusion.dev.CallTrace"> & {
  /**
   * Internal developer span name, often a function/method.
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * File name where the span was created.
   *
   * @generated from field: optional string file = 2;
   */
  file?: string;

  /**
   * Line number in the file where the span was created.
   *
   * @generated from field: optional uint32 line = 3;
   */
  line?: number;

  /**
   * Arbitrary extra structured data.
   *
   * @generated from field: map<string, v1.public.events.fusion.dev.DebugValue> extra = 4;
   */
  extra: { [key: string]: DebugValue };
};

/**
 * Describes the message v1.public.events.fusion.dev.CallTrace.
 * Use `create(CallTraceSchema)` to create a new message.
 */
export const CallTraceSchema: GenMessage<CallTrace> = /*@__PURE__*/
  messageDesc(file_dbtlabs_proto_public_v1_events_fusion_dev_dev, 1);

/**
 * Unknown span placeholder used as a fallback. Presence of this
 * event in the stream indicates a bug in the telemetry instrumentation.
 *
 * @generated from message v1.public.events.fusion.dev.Unknown
 */
export type Unknown = Message<"v1.public.events.fusion.dev.Unknown"> & {
  /**
   * Inferred name, often a function/method.
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * File name where the span was created.
   *
   * @generated from field: string file = 2;
   */
  file: string;

  /**
   * Line number in the file where the span was created.
   *
   * @generated from field: uint32 line = 3;
   */
  line: number;
};

/**
 * Describes the message v1.public.events.fusion.dev.Unknown.
 * Use `create(UnknownSchema)` to create a new message.
 */
export const UnknownSchema: GenMessage<Unknown> = /*@__PURE__*/
  messageDesc(file_dbtlabs_proto_public_v1_events_fusion_dev_dev, 2);

