// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file dbtlabs/proto/public/v1/events/fusion/log/compiled.proto (package v1.public.events.fusion.log, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file dbtlabs/proto/public/v1/events/fusion/log/compiled.proto.
 */
export const file_dbtlabs_proto_public_v1_events_fusion_log_compiled: GenFile = /*@__PURE__*/
  fileDesc("CjhkYnRsYWJzL3Byb3RvL3B1YmxpYy92MS9ldmVudHMvZnVzaW9uL2xvZy9jb21waWxlZC5wcm90bxIbdjEucHVibGljLmV2ZW50cy5mdXNpb24ubG9nIlgKDENvbXBpbGVkQ29kZRIVCg1yZWxhdGl2ZV9wYXRoGAEgASgJEgsKA3NxbBgCIAEoCRIRCgl1bmlxdWVfaWQYAyABKAkSEQoJbm9kZV9uYW1lGAQgASgJIiEKEkNvbXBpbGVkQ29kZUlubGluZRILCgNzcWwYASABKAlCPlo8Z2l0aHViLmNvbS9kYnQtbGFicy9wcm90by1nb2xhbmcvdjEvcHVibGljL2V2ZW50cy9mdXNpb24vbG9nYgZwcm90bzM");

/**
 * Log event that carries compiled SQL for a project node.
 *
 * `sql` may contain user data and may be scrubbed when sensitive telemetry
 * collection is disabled.
 *
 * @generated from message v1.public.events.fusion.log.CompiledCode
 */
export type CompiledCode = Message<"v1.public.events.fusion.log.CompiledCode"> & {
  /**
   * Path to the compiled SQL file, relative to project root (`in_dir`).
   *
   * @generated from field: string relative_path = 1;
   */
  relativePath: string;

  /**
   * Compiled SQL text. May be scrubbed.
   *
   * @generated from field: string sql = 2;
   */
  sql: string;

  /**
   * Globally unique dbt node identifier.
   *
   * @generated from field: string unique_id = 3;
   */
  uniqueId: string;

  /**
   * Display node name for compatibility output.
   *
   * @generated from field: string node_name = 4;
   */
  nodeName: string;
};

/**
 * Describes the message v1.public.events.fusion.log.CompiledCode.
 * Use `create(CompiledCodeSchema)` to create a new message.
 */
export const CompiledCodeSchema: GenMessage<CompiledCode> = /*@__PURE__*/
  messageDesc(file_dbtlabs_proto_public_v1_events_fusion_log_compiled, 0);

/**
 * Log event that carries inline compiled SQL code.
 *
 * @generated from message v1.public.events.fusion.log.CompiledCodeInline
 */
export type CompiledCodeInline = Message<"v1.public.events.fusion.log.CompiledCodeInline"> & {
  /**
   * @generated from field: string sql = 1;
   */
  sql: string;
};

/**
 * Describes the message v1.public.events.fusion.log.CompiledCodeInline.
 * Use `create(CompiledCodeInlineSchema)` to create a new message.
 */
export const CompiledCodeInlineSchema: GenMessage<CompiledCodeInline> = /*@__PURE__*/
  messageDesc(file_dbtlabs_proto_public_v1_events_fusion_log_compiled, 1);

