// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file dbtlabs/proto/public/v1/events/fusion/log/list_item.proto (package v1.public.events.fusion.log, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file dbtlabs/proto/public/v1/events/fusion/log/list_item.proto.
 */
export const file_dbtlabs_proto_public_v1_events_fusion_log_list_item: GenFile = /*@__PURE__*/
  fileDesc("CjlkYnRsYWJzL3Byb3RvL3B1YmxpYy92MS9ldmVudHMvZnVzaW9uL2xvZy9saXN0X2l0ZW0ucHJvdG8SG3YxLnB1YmxpYy5ldmVudHMuZnVzaW9uLmxvZyKNAQoOTGlzdEl0ZW1PdXRwdXQSRAoNb3V0cHV0X2Zvcm1hdBgBIAEoDjItLnYxLnB1YmxpYy5ldmVudHMuZnVzaW9uLmxvZy5MaXN0T3V0cHV0Rm9ybWF0Eg8KB2NvbnRlbnQYAiABKAkSFgoJdW5pcXVlX2lkGAMgASgJSACIAQFCDAoKX3VuaXF1ZV9pZCquAQoQTGlzdE91dHB1dEZvcm1hdBIiCh5MSVNUX09VVFBVVF9GT1JNQVRfVU5TUEVDSUZJRUQQABIbChdMSVNUX09VVFBVVF9GT1JNQVRfSlNPThABEh8KG0xJU1RfT1VUUFVUX0ZPUk1BVF9TRUxFQ1RPUhACEhsKF0xJU1RfT1VUUFVUX0ZPUk1BVF9OQU1FEAMSGwoXTElTVF9PVVRQVVRfRk9STUFUX1BBVEgQBEI+WjxnaXRodWIuY29tL2RidC1sYWJzL3Byb3RvLWdvbGFuZy92MS9wdWJsaWMvZXZlbnRzL2Z1c2lvbi9sb2diBnByb3RvMw");

/**
 * Event emitted for each item in a list command output.
 * This event replaces the dbt-core PrintEvent (Z052) for list operations.
 *
 * @generated from message v1.public.events.fusion.log.ListItemOutput
 */
export type ListItemOutput = Message<"v1.public.events.fusion.log.ListItemOutput"> & {
  /**
   * Format of the output
   *
   * @generated from field: v1.public.events.fusion.log.ListOutputFormat output_format = 1;
   */
  outputFormat: ListOutputFormat;

  /**
   * The actual content of the list item being displayed
   *
   * @generated from field: string content = 2;
   */
  content: string;

  /**
   * The unique_id of the node being listed (e.g., "model.my_project.my_model")
   *
   * @generated from field: optional string unique_id = 3;
   */
  uniqueId?: string;
};

/**
 * Describes the message v1.public.events.fusion.log.ListItemOutput.
 * Use `create(ListItemOutputSchema)` to create a new message.
 */
export const ListItemOutputSchema: GenMessage<ListItemOutput> = /*@__PURE__*/
  messageDesc(file_dbtlabs_proto_public_v1_events_fusion_log_list_item, 0);

/**
 * Output format for list command
 *
 * @generated from enum v1.public.events.fusion.log.ListOutputFormat
 */
export enum ListOutputFormat {
  /**
   * @generated from enum value: LIST_OUTPUT_FORMAT_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: LIST_OUTPUT_FORMAT_JSON = 1;
   */
  JSON = 1,

  /**
   * @generated from enum value: LIST_OUTPUT_FORMAT_SELECTOR = 2;
   */
  SELECTOR = 2,

  /**
   * @generated from enum value: LIST_OUTPUT_FORMAT_NAME = 3;
   */
  NAME = 3,

  /**
   * @generated from enum value: LIST_OUTPUT_FORMAT_PATH = 4;
   */
  PATH = 4,
}

/**
 * Describes the enum v1.public.events.fusion.log.ListOutputFormat.
 */
export const ListOutputFormatSchema: GenEnum<ListOutputFormat> = /*@__PURE__*/
  enumDesc(file_dbtlabs_proto_public_v1_events_fusion_log_list_item, 0);

