// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file dbtlabs/proto/public/v1/events/fusion/generic/generic.proto (package v1.public.events.fusion.generic, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file dbtlabs/proto/public/v1/events/fusion/generic/generic.proto.
 */
export const file_dbtlabs_proto_public_v1_events_fusion_generic_generic: GenFile = /*@__PURE__*/
  fileDesc("CjtkYnRsYWJzL3Byb3RvL3B1YmxpYy92MS9ldmVudHMvZnVzaW9uL2dlbmVyaWMvZ2VuZXJpYy5wcm90bxIfdjEucHVibGljLmV2ZW50cy5mdXNpb24uZ2VuZXJpYyJ1ChFHZW5lcmljT3BFeGVjdXRlZBIUCgxvcGVyYXRpb25faWQYASABKAkSFgoOZGlzcGxheV9hY3Rpb24YAiABKAkSHQoQaXRlbV9jb3VudF90b3RhbBgDIAEoBEgAiAEBQhMKEV9pdGVtX2NvdW50X3RvdGFsIoUBChZHZW5lcmljT3BJdGVtUHJvY2Vzc2VkEhQKDG9wZXJhdGlvbl9pZBgBIAEoCRIiChpkaXNwbGF5X2luX3Byb2dyZXNzX2FjdGlvbhgCIAEoCRIhChlkaXNwbGF5X29uX3N1Y2Nlc3NfYWN0aW9uGAMgASgJEg4KBnRhcmdldBgEIAEoCUJCWkBnaXRodWIuY29tL2RidC1sYWJzL3Byb3RvLWdvbGFuZy92MS9wdWJsaWMvZXZlbnRzL2Z1c2lvbi9nZW5lcmljYgZwcm90bzM");

/**
 * An event used for spans that represent the execution of an operation
 * that doesn't have a stable API and/or dedicated event type with
 * structured fields yet.
 *
 * @generated from message v1.public.events.fusion.generic.GenericOpExecuted
 */
export type GenericOpExecuted = Message<"v1.public.events.fusion.generic.GenericOpExecuted"> & {
  /**
   * Identifier for this operation type (e.g., "format", "lint")
   * Used as unique ID for associating child items
   *
   * @generated from field: string operation_id = 1;
   */
  operationId: string;

  /**
   * Display action text in lowercase (e.g., "formatting", "linting").
   *
   * Note: this may be capitalized when rendered and/or combined with
   * other text (e.g., "Started formatting 3 items...")
   *
   * @generated from field: string display_action = 2;
   */
  displayAction: string;

  /**
   * Total count of items (enables progress bar if > 0, otherwise spinner)
   *
   * @generated from field: optional uint64 item_count_total = 3;
   */
  itemCountTotal?: bigint;
};

/**
 * Describes the message v1.public.events.fusion.generic.GenericOpExecuted.
 * Use `create(GenericOpExecutedSchema)` to create a new message.
 */
export const GenericOpExecutedSchema: GenMessage<GenericOpExecuted> = /*@__PURE__*/
  messageDesc(file_dbtlabs_proto_public_v1_events_fusion_generic_generic, 0);

/**
 * An event used for spans emitted for each item processed as part of a
 * GenericOpExecuted operation.
 *
 * @generated from message v1.public.events.fusion.generic.GenericOpItemProcessed
 */
export type GenericOpItemProcessed = Message<"v1.public.events.fusion.generic.GenericOpItemProcessed"> & {
  /**
   * Must match the parent GenericOpExecuted.operation_id
   * Used to look up UID from the global mapping
   *
   * @generated from field: string operation_id = 1;
   */
  operationId: string;

  /**
   * Action text in lowercase (e.g., "formatting", "linting").
   * for in-progress display.
   *
   * Note: this may be capitalized when rendered and/or combined with
   * other text (e.g., "Started formatting {target}")
   *
   * @generated from field: string display_in_progress_action = 2;
   */
  displayInProgressAction: string;

  /**
   * Action text in lowercase (e.g., "formatted", "linted").
   * for on-success display.
   *
   * Note: this may be capitalized when rendered and/or combined with
   * other text (e.g., "Formatted {target}")
   *
   * @generated from field: string display_on_success_action = 3;
   */
  displayOnSuccessAction: string;

  /**
   * Display name shown in progress bar context (e.g., file path)
   *
   * @generated from field: string target = 4;
   */
  target: string;
};

/**
 * Describes the message v1.public.events.fusion.generic.GenericOpItemProcessed.
 * Use `create(GenericOpItemProcessedSchema)` to create a new message.
 */
export const GenericOpItemProcessedSchema: GenMessage<GenericOpItemProcessed> = /*@__PURE__*/
  messageDesc(file_dbtlabs_proto_public_v1_events_fusion_generic_generic, 1);

