// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file dbtlabs/proto/public/v1/events/fusion/compat/otlp.proto (package v1.public.events.fusion.compat, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file dbtlabs/proto/public/v1/events/fusion/compat/otlp.proto.
 */
export const file_dbtlabs_proto_public_v1_events_fusion_compat_otlp: GenFile = /*@__PURE__*/
  fileDesc("CjdkYnRsYWJzL3Byb3RvL3B1YmxpYy92MS9ldmVudHMvZnVzaW9uL2NvbXBhdC9vdGxwLnByb3RvEh52MS5wdWJsaWMuZXZlbnRzLmZ1c2lvbi5jb21wYXQqtgEKDlNldmVyaXR5TnVtYmVyEh8KG1NFVkVSSVRZX05VTUJFUl9VTlNQRUNJRklFRBAAEhkKFVNFVkVSSVRZX05VTUJFUl9UUkFDRRABEhkKFVNFVkVSSVRZX05VTUJFUl9ERUJVRxAFEhgKFFNFVkVSSVRZX05VTUJFUl9JTkZPEAkSGAoUU0VWRVJJVFlfTlVNQkVSX1dBUk4QDRIZChVTRVZFUklUWV9OVU1CRVJfRVJST1IQEUJBWj9naXRodWIuY29tL2RidC1sYWJzL3Byb3RvLWdvbGFuZy92MS9wdWJsaWMvZXZlbnRzL2Z1c2lvbi9jb21wYXRiBnByb3RvMw");

/**
 * Subset of OTLP LogRecord.SeverityNumber used by fusion.
 *
 * @generated from enum v1.public.events.fusion.compat.SeverityNumber
 */
export enum SeverityNumber {
  /**
   * Default value. Should not be used.
   *
   * @generated from enum value: SEVERITY_NUMBER_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: SEVERITY_NUMBER_TRACE = 1;
   */
  TRACE = 1,

  /**
   * @generated from enum value: SEVERITY_NUMBER_DEBUG = 5;
   */
  DEBUG = 5,

  /**
   * @generated from enum value: SEVERITY_NUMBER_INFO = 9;
   */
  INFO = 9,

  /**
   * @generated from enum value: SEVERITY_NUMBER_WARN = 13;
   */
  WARN = 13,

  /**
   * @generated from enum value: SEVERITY_NUMBER_ERROR = 17;
   */
  ERROR = 17,
}

/**
 * Describes the enum v1.public.events.fusion.compat.SeverityNumber.
 */
export const SeverityNumberSchema: GenEnum<SeverityNumber> = /*@__PURE__*/
  enumDesc(file_dbtlabs_proto_public_v1_events_fusion_compat_otlp, 0);

