# **what?**
# Open an issue in docs.getdbt.com when an issue is labeled `user docs` and closed as completed

# **why?**
# To reduce barriers for keeping docs up to date

# **when?**
# When an issue is labeled `user docs` and is closed as completed.  Can be labeled before or after the issue is closed.


name: Open issues in docs.getdbt.com repo when an issue is labeled
run-name: "Open an issue in docs.getdbt.com for issue #${{ github.event.issue.number }}"

on:
  push:
    branches:
      - ash2shukla/test/open-issues-in-repo-action

defaults:
  run:
    shell: bash

permissions:
    issues: write # comments on issues

jobs:
  open_issues:
    uses: dbt-labs/actions/.github/workflows/open-issue-in-repo.yml@ash2shukla/fix/comment-injection-in-open-issue-workflow
    with:
        issue_repository: "dbt-labs/dbt-core"
        issue_title: "Test open-issue-in-repo action changes"
        issue_body: "Testing action changes"
    secrets: inherit
